module.exports = {
  SITECOMMON: {
    INTERUPTOR_POPUP_WINDOW: '#popup-content',
    INTERUPTOR_POPUP_CLOSE: '#popup-close'
  },
  productPage: {
    SKU_NUM: '.sku-number >> nth=0',
    SKU_DESCRIPTION: '(//h1[@class="product-name text-xl-bold"])[1]',
    SKU_PRICE_REGULAR: '(//*[@class="regPrice"])[2]',
    SKU_PRICE_SALE: '(//*[@class="salePrice"])[1]',
    // SKU_NUM: 'span.sku-number',
    // SKU_NUM: '//span[@class="sku-number"]',
    // SKU_DESCRIPTION: '[class="product-name text-xl-bold"]',
    SKU_PRICE: '[class="regPrice"]',
    ADDTOCART_BUTTON: '//div[@class="add-to-cart-button-container"]/span/button[@id="addToCartButton"]',
    CHECKOUTNOW_BUTTON: '[class*="button-checkout-now"]',
    CHECKOUTNOW_BUTTON1: '[class="button button-lg button-primary"]',
    quickShip: 'button[data-testid="quickship-button"]',
    quickShipTitle: '//div[@class="popup-heading"]/h1',
    quickShipZipcode: '//div[@data-testid="quickship-availability"]',
    quickShipClose: '//button[@id="popup-close"]',
    depthSelectedChoice: '//div[@data-region="sor-depth-option"]/div/div[@class="accordion-sor-description text-md-reg"]',
    sizeSelectedChoice: '//div[@data-region="sor-size-option"]/div/div[@class="accordion-sor-description text-md-reg"]',
    fabricSelectedChoice: '//div[@data-region="sor-fabric-option"]/div/div[@class="accordion-sor-description text-md-reg"]',
    txtProductSummary: '//*[@id="summary-custom-product"]',
    skuTitle: '//div[@class="hidden-xs"]/div/h1[@class="product-name text-xl-bold"]',
    onDisplayLink: '//div[@class="display-in-store"]/button',
    onDisplayHeader: '//h2[@class="store-availability-header"]',
    zipCodeField: '//div[@class="header-zip-container"]/button[@class="button-transparent zip-code-display"]',
    fabricSortFilter: '//div[@class="filter-fabric-accordion-header"]',
    colorFilter: '//div[@data-testid="checkbox"]/label/span[contains(text(), "Grey, Black")]',
    filterApply: '//button[@class="button button-lg button-primary button-done-filter"]',
    fabricSelectedFilter: '//span[@class="filter-fabric-shortcut-label text-md-reg"]',
    detailsDrawerText: '//div[@class="details-dimensions"]',
    detailsDrawer: '//div[@class="drawer-header"]/div[contains(text(),"Details")]',
    reviewsDrawer: '//div[@data-id="reviews-drawer"]',
    dimesionsDrawer: '//div[@data-id="dimensions-drawer"]',
    careDrawer: '//div[@class="drawer-header"]/div[contains(text(),"Care")]',
    partOfCollectionCarousel: '//h2[contains(text(),"Part of a Collection")]',
    partOfCollectionItems: '//a[@class="showcase-item-link"]/h3',
    crateStyleCarousel: '//div[@class="showcase-title"]/h2[contains(text(),"#CrateStyle")]',
    peopleAlsoViewedCarousel: '//h2[contains(text(),"People Also Viewed")]',
    recentlyViewed: '//h2[contains(text(),"Recently Viewed")]',
    depthDrawerLbl: '[data-region=sor-depth-option]',
    // DEPTH_DRAWER_LBL_SELECT_DESC: ':nth-child(1) > .a11y-drawer-toggle > button > :nth-child(1) > .accordion-sor-header > .accordion-sor-content-container > .accordion-sor-description',
    depthDrawerLblSelectDesc: 'label:has-text("Deep: 43")',
    sizeDrawerLbl: '[data-region="sor-size-option"]',
    // SIZE_DRAWER_LBL_SELECT_DESC: ':nth-child(2) > .a11y-drawer-toggle > button > :nth-child(1) > .accordion-sor-header > .accordion-sor-content-container > .accordion-sor-description',
    sizeDrawerLblSelectDesc: 'label:has-text("98")',
    fabricDrawerLbl: '[data-region="sor-fabric-option"]',
    // FABRIC_DRAWER_LBL_SELECT_DESC: ':nth-child(3) > .a11y-drawer-toggle > button > :nth-child(1) > .accordion-sor-header > .accordion-sor-content-container > .accordion-sor-description',
    fabricDrawerLblSelectDesc: 'label:has-text("Steel")',
    GET_FREE_SWATCH_BUTTON: 'button[class="button-transparent get-swatch-btn a11y-link"]',
    FREE_SWATCH_POPUP_CLOSE_BUTTON: 'button[class="button button-secondary button-xl popup-close"]',
    QuantityMinusButton: 'button-quantity-decrease',
    QuantityPlusButton: 'button-quantity-increase',
    QUANTITY_VALUE: '#qty-141734',
    SHIPIT_TEXT: '//*[contains(@class,"secondary-message")]//span',
    SKU2_SHIPIT_TEXT: '//*[@class="secondary-message secondary-message-contain-promo"]//span',
    // btnMainAddToCart: '#addToCartButton >> nth=0',
    MainBtnAddToCart: 'add-to-cart-button',
    // btnMainAddToCart: 'div.add-to-cart-button-container > span > button[data-testid="add-to-cart-button"]',

    btnMainAddToCartTestId: 'button[data-testid="add-to-cart-button"]',
    lblProductSummary: '//*[@id="summary-custom-product"]',
    lblMtoProductSummary: 'div#popup-content div#summary-custom-product',
    lblMtoMessageOnPdp: '//div[@class="zip-code-message"]',
    btnMtoClose: '//button[@id="popup-close"]',
    btnMtoAddToCart: '//button[@data-id="addToCartButton"]',
    btnMtoDecline: '//button[@class="dsButton_1r2-k dsButtonSecondary_1B2l5 dsButtonXl_3vFQP button-decline"]',
    btnMtoCB2Decline: '//button[@class="dsButton_3rImP dsButtonSecondary_ex3CB dsButtonXl_ZoLC0 button-decline"]',
    btnMtoAccept: '.button-container [data-id="addToCartButton"]',
    lblMtoTerms: '//div[@class="terms"]',
    lblMtoPopupTitle: '//h2[@class="title"]',
    imgMtoProduct: '//img[@class="product-image"]',
    btnAddToRegistry: '//button[@value="addToRegistry"]',
    confModel: '//h2[@class="m-conf-item-count"]',
    btnViewYourRegistry: '//*[@id="_tagRegistryTotals"]//a',
    btnAddToFavorite: '[class="button-add-to-favorite button button-secondary button-xl nsInt"]',
    // btnMyFavorites: '[class="design-list button-transparent"]',
    btnMyFavorites: 'li[data-testid=list-item-0] button',
    lnkViewFavorites: '.view-list-message',
    imgItem: '.added-img',
    popUpSkuTitle: 'h3[class*=productInfoTitle]',
    btnCreateNew: 'div[class*=newListRow] button',
    msgAddedFavorites: '#jsConfirmBoard',
    lblArrivesMessage: '.availMsg.warning.product-backorder',
    lblAvailabilityMessage: '.warning.fcRed.product-backorder',
    // lblInstockAvailabilityMessage: '.zip-code-message > span > span',
    lblInstockAvailabilityMessage: '.zip-code-message > span',
    //    lblInstockAvailabilityMessage: '.zip-code-message > span > span',
    lblGrouperColor: '//span[contains(text(), "Color")]',
    lblGrouperSize: '//span[contains(text(), "Size")]',
    rdShip: '//label[contains(text(), "Ship It")]',
    rdPickUpAtStore: '//label[contains(text(), "FREE CURBSIDE PICKUP AT STORE")]'
  },
  freeShippingPopup: {
    hdrFreeShippingPopup: '[class="crate-helvetica-roman cmsBlack promoHead"]',
    hdrSubFreeShippingPopup: '[class*="pop-sub"]',
    msgFreeShippingPopup: '[class="crate-helvetica-roman tAndC"]',
    hdrCB2FreeShippingPopup: '[class="free-shipping-cms-popup"] > h1',
    hdrCB2SubFreeShippingPopup: '[class="free-shipping-cms-popup"] > h2',
    msgCB2FreeShippingPopup: '[class="cb2-brown-light"]',
    divPopupContainer: '#popup-container'
  }
};
