module.exports = {
  common: {
    btnPopupClose: '#popup-close'
  },
  cartPage: {
    arrayCartItemElements: '[data-testid=cart-product-line-item-row]',
    lblArrivesByMessage: '[data-testid=delivery-time] > button > span:nth-child(1)',
    lblCartSkuCount: '[data-testid=item-count]',
    lblCartSkuNum: '[data-testid=item-sku]',
    lblCartSkuQuantity: '[data-testid=price-quantity-totals-input]',
    lblCartSkuPrice: '[data-testid=item-price]',
    lblCartSaleRegularSkuPrice: '[data-testid=total-price]',
    lblFavouritesItemCount: '[data-testid=favorites-count]',
    lblCartSkuDescription: '[data-testid=item-title]',
    lblOrderSummaryGiftBoxTotal: '[data-testid=gift-box-row-amt] [data-testid=formatted-price]',
    btnGuestCheckout: '[data-testid=button-guest-checkout]',
    lblOrderSummaryMerchandiseDiscountTotal: '[data-testid=merchandiseDiscount-amt] [data-testid=formatted-price"]',
    lblOrderSummaryMerchandiseTotal: '[data-testid=total-amt] [data-testid=formatted-price]',
    lblOrderSummaryOrderTotal: '[data-testid=est-total-row-remaining-total-amt] > [data-testid=formatted-price]',
    lblOrderSummaryEstShippingDiscountTotal: '[data-testid=shippingDiscount-amt] [data-testid=formatted-price]',
    lblOrderSummaryEstShippingHandlingTotal: '[data-testid=est-shipping-handling-total] > .col-xs-3 > span',
    lblOrderSummaryTaxTotal: '[data-testid=order-summary-tax-total-amt] [data-testid=formatted-price]',
    btnSubmitPaypal: '[class="paypal-button-label-container"]',
    lblAgreementNote: '#agreement-note-top',
    lblAgreementNoteText1: '#agreement-note-top >> nth=0',
    lblAgreementNoteText2: '#agreement-note-top >> nth=1',
    lblPrivacyPolicy: '#agreement-note-top >> text=Privacy Policy',
    // lblReturnsMadeEasyContentText: 'p >> nth=0',
    lblReturnsMadeEasyContentLinks: 'p >> nth=1',
    lblDrawerFreePickup: '.a11y-drawers',
    lblFreeStoreAndWarehousePickupContentHdr: 'h2',
    // lblFreeStoreAndWarehousePickupContentText: 'p >> nth=0',
    lblFreeStoreAndWarehousePickupContentLinks: 'p >> nth=1',
    lblDrawerInternational: '.a11y-drawers >> nth=2',
    lnkTermsOfUse: 'a[href="/customer-service/terms-of-use"]',
    btnProceedToCheckout: '[data-testid=proceed-to-checkout]',
    // lblCartAvailabilityMsg: '[data-testid=cart-availablity-msg]', //missing
    lblCartAvailabilityMsg: '[class="availability"]',
    // lblSalePriceElement: '#price > .sale',
    lblSalePriceElement: '.sale',
    // lblSalePrice: '#price > .sale > .salePrice',
    lblSalePrice: '.sale > .salePrice',
    lblCartItemCount: '[data-testid=header-cart-count], [data-testid=cart-count]',
    lblAdditionalChargesMsg: '[data-testid=lbl-additional-charge-msg]',
    btnOversizeShippingCharges: '[data-testid=btn-oversize-shipping-charges]',
    lblOversizeShippingPopupMsg: '#divAddCharge',
    btnRemove: '[data-testid=remove-from-cart-btn]',
    btnSaveForLater: '[data-testid=cart-save-for-later-btn]',
    rdShip: '[data-testid=ship-radio-btn]',
    lblShippingDeliveryMethod: '[class="shipping-avail-messages indent"] > li:nth-child(2) > button > span:nth-child(1)',
    txtTermsOfUse: '#agreement-note-top >> text=Terms of Use',
    btnVenmoPayment: '[data-testid=cart-venmo-button]',
    lnkZipCode: '[data-testid=lnk-zip-code] >> nth=0',
    btnSubmitZipCode: '[data-testid=btn-submit-zipcode]',
    txtZipCode: '#zipcode-input',
    btnCheckoutNow: '[data-testid=proceed-to-checkout]',
    lblPromoCodeHeader: '[data-testid=promo-code-header]',
    txtPromoCode: '#txtPromoCode',
    btnApplyPromoCode: '#applyPromo',
    lblInvalidPromoError: '#errorMessage',
    hdrCartBannerPromo: '.promoHeadline',
    txtCartBannerPromo: '.promoText',
    lnkCartBannerPromo: '.promoLink >> nth=2',
    // lblGiftMessageContent: '[data-testid=gift-message]', //missing
    lblGiftMessageContent: '[class="gift-message"]',
    lblSpecialDeliveryMessagingHeader: '.messaging >> h2 >> nth=0',
    lblSpecialDeliveryMessagingText: '.messaging >> p >> nth=0',
    lnkSpecialDeliveryMessagingText: '.messaging >> a >> nth=0',
    btnTxtShippingDeliveryRate: '[data-testid=btn-txt-shipping-delivery-rate]',
    SkuNum: '.sku-number >> nth=0',
    SkuDescription: '(//h1[@class="product-name text-xl-bold"])[1]',
    SkuPriceRegular: '(//*[@class="regPrice"])[1]',
    SkuPriceSale: '(//*[@class="salePrice"])[1]',
    SkuPrice: '[class="regPrice"]',
    textSkuElement: '[data-testid="text-element"]',
    fontSku: '[class="text-md-reg selected-font"]',
    threadSku: '[class="text-md-reg selected-color"]',

    lblDrawers: '.a11y-drawers',
    // lblDrawerSpecialLocalHomeMsg: '.a11y-drawers >> nth=0',
    lblSpecialLocalHomeMsgHdr: '#specialLocalInHomeMessaging > h2',
    lblSpecialLocalHomeMsgText: '#specialLocalInHomeMessaging > p',
    lblSpecialLocalHomeMsgLink: '#specialLocalInHomeMessaging > a',

    lblDrawerReturnPolicy: '.a11y-drawers >> nth=0',

    lblReturnsMadeEasyContentHeader: '.promo-container >> .hidden-xs >> .messaging >> h2 >> nth=0',
    lblReturnsMadeEasyContentText: '.promo-container >> .hidden-xs >> .messaging >> p >> nth=0',
    lnkReturnsMadeEasyContentText: '.promo-container >> .hidden-xs >> .messaging >> a >> nth=0',
    lblReturnsMadeEasyContentMobText: '.a11y-drawer-wrap > .a11y-drawer-panel > div > p >>nth=0',

    lblFreeStoreAndWarehousePickupContentAccordion: '#cart-accordion-pickup',
    lblFreeStoreAndWarehousePickupContentTextMob: '.a11y-drawer-panel > div > p >> nth=0',
    lnkFreeStoreAndWarehousePickupContentLinkMob: '.a11y-drawer-panel > div > p > a',

    lblFreeStoreAndWarehousePickupContentHeader: '.promo-container >> .hidden-xs >> .messaging >> h2 >> nth=1',
    lblFreeStoreAndWarehousePickupContentText: '.promo-container >> .hidden-xs >> .messaging >> p >> nth=1',
    lnkFreeStoreAndWarehousePickupContentText: '.promo-container >> .hidden-xs >> .messaging >> a >> nth=1',

    lblInterNationalShippingContentHeader: '',
    lblInterNationalShippingContentText: '.promo-notes > p',
    lnkInterNationalShippingContentText: '',
    lblSaveForLaterSection: '#savedForLater',
    hdrSaveForLater: '//div/h2[@class="page-title"]',
    txtSaveForLater: '[class*=agreement-note]',
    lblSaveForLaterItemDescription: '[data-testid=save-for-later-item-description]',
    lblSaveForLaterItemPrice: '[data-testid=save-for-later-item-price]',
    lblSaveForLaterAvailabilityMsg: '[data-testid=save-for-later-item-availability]',
    btnMoveToCart: '[data-testid=btn-move-to-cart]',
    btnSaveForLaterClose: '[data-testid=btn-save-for-later-close]',
    lblSaveForLaterItemCount: '[data-testid=save-for-later-item-count]',
    lblProductListRemoveMsg: '[data-testid=cart-list-item-removed-msg]',
    lblAddSaveForLaterMsg: '[data-testid=save-for-later-remove-msg]',
    lblCartSignIn: '[data-testid=lbl-cart-sign-in]',
    lblMobileCartSignIn: '[class*=button-sigin]',
    txtMobileSaveForLater: '[data-testid=txt-save-for-later]',
    hdrCartCount: '[data-testid=cart-count]',
    containerItemRemoved: '[data-testid=toast-message]', //  '[data-testid=cart-list-item-removed-msg] 12/13
    txtItemMovedToCart: '#save-for-later-remove-msg', // '[data-testid=txt-item-removed]', 12/13
    lnkItemRemoved: '[data-testid=lnk-item-removed]',
    CheckoutButton: '.button-checkout-now',
    txtCartOrderSummaryCountMsg: '[data-testid=item-count]',
    btnIncrementItemQuantity: '[data-testid=price-quantity-totals-increase]',
    btnDecrementItemQuantity: '[data-testid=price-quantity-totals-decrease]',
    inputItemQuantity: '[data-testid=price-quantity-totals-input]',
    lnkShipping: '//li/span[text()="Shipping:"]//parent::li/button/span[1]',
    txtLIHFOU999: '//div[@Id="popup-container"]//table[1]//th[1]',
    txtLIHUpto100Mil: '(//div[@Id="popup-container"]//tbody[1]/tr[1]/td[1])[1]',
    txtShippingPopUpHeader: '//div[@id="shipping-charges-tab"]//h3',
    txtLIHOver100Mil: '(//div[@Id="popup-container"]//tbody[1]/tr[2]/td[1])[1]',
    txtLIHUnlimitedHeader: '//div[@Id="popup-container"]//table[2]//th[1]',
    txtLIHUnlimted: '//div[@Id="popup-container"]//table[2]//th[1]',
    txtLIHULUpto100Mil: '(//div[@Id="popup-container"]//tbody[1]/tr[1]/td[1])[2]',
    txtLIHULOver100Mil: '(//div[@Id="popup-container"]//tbody[1]/tr[2]/td[1])[1]',
    txtbftShippingCharge: '#shipping-charges-tab >> p',
    txtldDelivery: '(//div[@id="shipping-charges-tab"]//h3)[1]',
    txtldShippingCharge: '(//p[@id="divLocalDeliveryCharge"]//h3)[2]',
    txtldShippingAmount: '//span[@id="lblCharge"]',
    btnPopUpClose: '//button[@id="popup-close"]',
    txtCartShippingAmount: '(//div[@class="order-summary row"]//span[@class="col-xs-3 amount"])[2]/span',
    txtbfShippingAmountCB2: '(//tbody//tr)[3]/td',
    txtbfShippingAmountCB: '(//tbody//tr)[2]/td',
    txtLDShippingAmount: '//span[@id="lblCharge"]',
    btnExpandDeliveryDetails: '//button//div[text()="Delivery Details"]',
    txtDeliveryPopUpHeader: '//div[@id="delivery-details-tab"]//h3',
    arrayShippingDeliveryElements: '//div[@id="delivery-details-tab"]//li',
    txtDeliverDetails: '//div[@id="delivery-details-tab"]//ul',
    btnExpandDIDetails: '//button//div[text()="Domestic and International"]',
    txtDeliveryDI: '//div[@id="international-delivery-tab"]',
    txtZipCodetxt: '(//button[@data-testid="lnk-zip-code"])[1]',
    altPaymentsContainer: '#alt-pay-options',
    txtAppliedPromoCode: '.applied-promo>.applied-promo-value',
    btnRemovePromo: 'button.button-remove-promo',
    lblShippingAvailabilityMessages: '[data-testid=shipping-avail-messages] > li > span',
    lblShippingAvailabilityMessage: '[data-testid=shipping-avail-messages] > li',
    lnkShippingDeliveryMethod: '[data-testid=btn-txt-shipping-delivery-rate]',
    txtAddToCartTermsContent: '[data-testid=txt-add-to-cart-terms-content]',
    btnAddToCartTermsDialog: '[data-id=addToCartButton]',
    txtCANDeliverDetailsLIH: '//div[@id="shipping-charges-tab"]/div',
    txtCANDeliverDetailsLIHtable: '//div[@id="shipping-charges-tab"]//table[2]',
    txtCANBFDHeaderText: '//div[@id="shipping-charges-tab"]',
    lblCb2Favourites: '//*[@class="svg-icon-heart-outline"]',
    lblCb2AddToFavourites: '//*[@class="svg-icon-heart-solid"]',
    divPopupContainer: '#popup-container',
    btnOversizePickupDesk: '[data-testid=btn-oversize-continue-hidden]',
    btnOversizePickupMob: '[data-testid=btn-oversize-continue-visible]',
    rdPickup: '[data-testid=pickup-radio-btn]',
    btnShippingCharges: '//div[@class="shipping-delivery-popup-content"]/div[1]/h2/button',
    hdrStandardDeliveryFee: '[id=shipping-charges-tab] >> h3 >> nth=0',
    msgUSStandardDeliveryFee: '#shipping-charges-tab >> li',
    msgCAStandardDeliveryFee: '#shipping-charges-tab >> p',
    hdrUSShippingDestinations: '#shipping-charges-tab > div > div > div > div > h3',
    hdrCAShippingDestinations: '#shipping-charges-tab >> h4',
    tblShippingRates: '[id=shipping-charges-tab] >> table >> nth=0',
    btnDeliveryDetails: '//div[@class="shipping-delivery-popup-content"]/div[2]/h2/button',
    hdrStandardDeliveryDetails: '[id=delivery-details-tab] >> h3',
    msgStandardDeliveryDetails: '[id=delivery-details-tab] >> p >> nth=0',
    msgCAStandardDeliveryDetails1: '[id=delivery-details-tab] >> p >> nth=1',
    msgCAStandardDeliveryDetails2: '[id=delivery-details-tab] >> p >> nth=2',
    tblShippingDetails: '[id=delivery-details-tab] >> table',
    btnCloseShippingPopUp: '#popup-close',
    tblAHShippingRates: '[id=shipping-charges-tab] >> table >> nth=1',
    lnkFreePickup: '[class="button-transparent location-link"]',
    lblPickupAvailable: '[data-testid="shipping-avail-messages"] > li > div',
    lblPickupAlert: 'p.alert',
    btnZipcodeSubmit: 'button#zipcode-submit-button',
    lblShippingCharges: '[data-testid="est-shipping-handling-total"] [data-testid="formatted-price"]',
    lblTax: '[data-testid="order-summary-tax-total-amt"] [data-testid="formatted-price"]',
    lblArrivesMessage: '.availMsg.warning.product-backorder',
    secCartProdyctCarousel: '#cross-sells-showcase-track',
    btnCarouselItem1: '#cross-sells-showcase-slide-1',
    lnkCarouselSkuDesc: '[data-testid="product-card-anchor-link-title"]',
    lnkCarouselSkuNum: '[data-testid="product-card-anchor-link-title"]',
    lnkCarouselSkuPrice: '[class *= dsProductCardPriceContent] > span',
    lnkCarouselSkuSalePrice: '.salePrice',
    btnCarouselAddToCart: '[data-testid=btn-cross-sell-add-to-cart]',
    txtCarouselToastMessage: '[data-testid=cart-item-added-message]', // [data-testid=cart-item-message-message]' 12/13 locator
    btncarouselToastView: '[data-testid=toast-message-view-button]', //  .cart-item-message-view-btn > button 12/13 locator
    btnCarouselItem2: '#cross-sells-showcase-slide-2',
    btnCarouselClose: '[data-testid=toast-message-message-close]', //  [data-testid=cart-item-message-close] 12/13 locator
    lblPickUpLocationNames: '.slide-open',
    btnPickUpLocations: '.slide-btn',
    lblPickUpAvailability: '.success',
    btnSelectLocation: 'a:text("Select This Location")',
    divPickUpModal: 'div.store-pickup-modal',
    hdrpickUpPopup: '.store-pickup-modal > h2',
    msgPickupPopup: '.store-pickup-modal > p',
    btnPickUpHelp: '[class="lnk-details button-transparent"]',
    msgPickupFAQ: '[class="responsive-stores store-pickup-faq cart-store-pickup"]',
    hdrPickupFAQ: '[class="responsive-stores store-pickup-faq cart-store-pickup"] >> h1',
    chkIncludeWarehouse: '#chkIncludeWarehouse',
    lblFreeStorePickupWithRadioButton: '[class*="radioBtnLabel"] > span',
    lblFreeWarehousePickupWithRadioButton: '[class*="radioBtnLabel"] > span',
    msgWarehousePickup: '.bops-option-warehouse-pickup-message',
    lnkLearnMore: '[data-testid="help-tooltip-button"]',
    msgStoreAvailability: '[data-testid = "shipping-avail-messages"] >> div',
    msgWarehouseAvailability: '[data-testid = "shipping-avail-messages"] >> div >> nth=3',
    lblFreeWarehousePickupWithoutRadioButton: '[class= "shipping-detail free-warehouse-shipping"] >> span >> nth=0',
    lblFreeStorePickupWithoutRadioButton: '[class = "shipping-detail free-shipping-detail"] >> span >> nth=0',
    msgStoreAvailWhenWarehouseSelected: '.shipping-avail-messages >> div',
    msgWarehouseLearnMoreToolTip: '#bops-option-warehouse-pickup-tooltip'
  },
  cartFlyOut: {
    txtReturningUserEmail: '#okta-signin-username',
    txtReturningUserPassword: '#okta-signin-password',
    btnSignInForReturningUser: '#okta-signin-submit',
    lblCheckoutTitle: '[data-testid=checkout-title]'
  },
  cartHeader: {
    lblCartCount: '[data-testid=header-cart-count]'
  },
  orderSummary: {
    lblOrderSummaryMerchandiseTotal: '[data-testid=order-summary-merchandise-total] [data-testid=formatted-price]',
    lblOrderSummaryGiftBoxTotal: '[data-testid=gift-box-row-amt] [data-testid=formatted-price]',
    lblOrderSummaryEstShippingHandlingTotal: '[data-testid=order-summary-shipping-handling-total] [data-testid=formatted-price]',
    lblOrderSummaryEstShippingDiscountTotal: '[data-testid=shippingDiscount-amt] [data-testid=formatted-price]', // '.alert discount > .col-xs-4 > span',
    lblOrderSummaryTaxTotal: '[data-testid=order-summary-tax-total-amt] [data-testid=formatted-price]',
    lblOrderSummaryOrderTotal: '[data-testid=order-summary-est-total] [data-testid=formatted-price]',
    lblOrderSummaryRewardsDollarTotal: '[data-testid=order-summary-rewards-total] [data-testid=formatted-price]' // .order-summary-rewards-message > :nth-child(2)'
  },
  checkoutPage: {
    lblCheckoutNavigationList: '[class="navigation-list"]',
    lblCheckoutNavigationShipping: 'span:has-text("Shipping and Gift Options")',
    lstCheckoutNavigationList: 'navigation-list',
    lstCheckoutNavigationListByDataTestId: "[data-testid='navigation-list']",
    txtNavigationShippingGifting: 'step-text-shipping-n-gift-opts',
    frmReferalProgram: "//*[@title='Referral program'] | //*[@name='talkable-offer-iframe-popup']",
    btnCloseReferalPopup: "//div[@class='popup-close is-custom js-offer-close'] | //div[@class='popup-close js-offer-close is-solid']",
    frmFeedbackSurvey: '[title="Feedback Survey"]',
    btnCloseMedaliaPopup: 'button[data-aut="button-x-close"]'
  },
  shippingAndGiftingPage: {
    lblShipToSingleUsrHeader: 'section-title-shipping-single-address',
    lnkMultiRecipient: '.shipping-address-toggle-button.button-as-link.button-transparent',
    lblShipToAddress: 'ship-to-address',
    lblMultiAddrTitle: '.shipping-multi-title',
    multipleNewAddr: '.button-add',
    selectedAddrbutton: '.selected-address-list > .button-container > button',
    selectedAddressDetail: '.selected-address-list > .text-container',
    addressList: '.other-address-lists > .address-list',
    lblShipItemsHdr: 'ship-items-hdr',
    lnkEditShipAddress: '.button-transparent.button-edit.button-as-link',
    arrayItems: '.review-item',
    lblItemTitle: 'item-title',
    lblItemQuantity: 'item-quantity',
    divAvsPopupContainer: '.avs-popup-container',
    divButtonHiddenAvsPopupMob: '.button-container.hidden-xs',
    divButtonHiddenAvsPopup: '.button-container.visible-xs',
    lblShippingMethodHdr: '[data-testid=lbl-shipping-method-hdr]',
    lblShippingMethodPolicy: '.sub-section-content.shipping-method-content > div > p',
    arrayShipMethods: '.shipping-list',
    // rdoShipMethodName: '.shipping-list > .a11y-radio',
    // lblShipMethodName: '.shipping-list > .a11y-radio-label.label-large',
    lblShipMethodArrivesBy: '.shipping-list > .arrival',
    divShippingMethodSection: '.shipping-method-section',
    rdoShipMethodName: 'rdo-ship-method-name',
    lblShipMethodName: 'ship-method-name-label',
    lblShipMethodDefault: 'ship-method-default',
    // lblShipMethodDefault: '.selected-shipping-method',
    lblDefaultStandardShipMode: '[data-testid=ship-method-default] > [data-testid=formatted-price]',
    lblShipMethodStandard: '.shipping-select-list >> text=Standard',
    lblShipMethodPremium: '.shipping-select-list >> text=Premium',
    lblShipMethodExpress: '.shipping-select-list >> text=Express',
    lblShipMethodStandardCharge: '.shipping-select-list >> text=Standard >> [data-testid=formatted-price]',
    lblShipMethodPremiumCharge: '.shipping-select-list >> text=Premium >> [data-testid=formatted-price]',
    lblShipMethodExpressCharge: '.shipping-select-list >> text=Express >> [data-testid=formatted-price]',
    lblShipMethodArrivesMsg: '.shipping-select-list > .shipping-list > .arrival',
    lblGiftOptionsHdr: '[data-testid=lbl-gift-options-hdr]',
    lblShipToFirstName: '#FirstName',
    lblShipToLastName: '#LastName',
    lblShipToAddress1: '#Address1',
    lblShipToZipCode: '#ZipCode',
    lblShipToCity: '#City',
    lblShipToState: '#State',
    lblShipToPhoneNum: '#DaytimePhone',
    btnShipAddressNext: '[data-testid=btn-proceed-to-shipping]',
    lblAvsPopupTitle: '[data-testid=lbl-avs-popup-title]',
    lblAvsDesc: '.avs-margin-top',
    lblAVSWeFound: '[class="section big-top-border we-found"]',
    lblAVSYouEnter: '[class="section big-top-border you-enter"]',
    buttonAVSSelection: '[class="button-address-display button-transparent"]',
    btnConfirmAvsPopupMob: '(//button[@data-testid="btn-confirm-avs-popup"])[1]',
    btnConfirmAvsPopup: '(//button[@data-testid="btn-confirm-avs-popup"])[2]',
    txtReceiptEmail: '#receiptEmail',
    btnProceedToPayment: '[data-testid=btn-proceed-to-payment]',
    checkboxUseAsBilling: '[data-testid=input--use-as-billing-address]',
    lblUseAsBilling: '[data-testid=label-use-as-billing-address]',
    lblGiftOptionsMessageContent: '[data-testid=lbl-gift-options-message-content]',
    lblGiftOptionsMessageHdr: '[data-testid=lbl-gift-options-message-hdr]',
    lblGiftOptionsSpecialCharWarning: '[data-testid=lbl-gift-options-special-char-warning]',
    lnkGiftOptionsViewDetails: 'data-testid=gift-box-option-view-details',
    lblGiftBoxedItemsHdr: '[data-testid=lbl-gift-boxed-items-hdr]',
    lblGiftBoxPolicy: '[data-testid=lbl-gift-box-policy]',
    rdoNoThisIsNotaGift: '[data-testid=rdo-no-this-is-nota-gift]',
    rdoYesThisIsGift: '#IsGift_True_2',
    lblYesThisIsGiftOption: '[data-testid=lbl-yes-this-is-gift-option]',
    txtGiftMessageBox: '#gift-message-message',
    // lblPresentYourGiftText: '[data-testid=lbl-present-your-gift-text]', //this is missing in DOM
    lblPresentYourGiftText: '[class="gift-message"]',
    imgCrateAndBarrel: '[data-testid=img-crate-and-barrel]',
    chkAddGiftBox: '[data-testid=chk-add-gift-box]',
    giftBoxChk: '[data-testid=gift-box-option-add-gift-box]',
    giftBoxSelectList: '.gift-checks > .gift-item-checkbox.a11y-checkbox',
    giftBoxSelect: '.gift-checks > .gift-item-checkbox.a11y-checkbox-label',
    shippingPageSelectBreadCrumbs: '[data-testid=shipping-page-select-bread-crumbs]',
    divRegistryItem: 'div.item-registry-info',
    rdoShipToOtherAddress: 'input#ship-to-other-address',
    divShipToAddressContainer: 'div.shipping-address-field-container',
    lblShipToOtherAddress: 'label[for="ship-to-other-address"]'
  },
  paymentPage: {
    pymtSelectCCBtn: '#credit-debit-card-label',
    pymtSelectPaymentMethods: '#other-payment',
    lnkPayWith2CreditCards: '#payWithTwoEnableWrapper',
    txtPymtCC: '[class="input-md applied-credit-card-credit-card-number "]',
    pymtSelectMasterCard: 'text=MasterCard ***5454',
    pymtSelectVisaCard: 'text=Visa ***111',
    pymtSelectUpdateBtn: 'text=Update Payment',
    txtPymtFirstCardAmt: '#Amountcard-1',
    txtPymtSecondCardAmt: '#Amountcard-2',
    txtPymtExpiry: '#expiration-date-input',
    txtpymtCVV: '#security-code-input-card-1',
    lblSelectedCardType: '.card-number',
    lblSavedMasterCard: 'text=MasterCard ***5454',
    lblSavedVisaCard: 'text=Visa ***111',
    lblSavedAmexCard: 'text=AmericanExpress ***1006',
    btnUpdatePayment: 'text=Update Payment',
    btnSelectCreditCardAsPayment: '#credit-debit-card-label',
    btnCheckoutHeader: 'div.brand-logo-checkout-header a',
    lnkPayWithTwoCreditCards: '#payWithTwoEnableWrapper',
    txtAmountSecondCard: '#Amountcard-2',
    txtNewCreditCardNumber: '.applied-credit-card-credit-card-number',
    txtCreditCardNumber: '#creditCardInfoWrapper > fieldset > input',
    txtExpiryDate: '#expiration-date-input',
    arrayCreditCards: '.credit-card-container .card-info',
    // txtCvv: '#SecurityCode-card-1',
    // txtCvv: '[class="security-code input-md jsSecurityCodeForEntry input-validation-valid"]',
    txtCvv: '#security-code-input-card-1',
    txtCvvPop: '#security-code-input-0',
    btnPymtApplyCard: '[data-testid=btn-pymt-apply-card]',
    btnPymtApplyCardMob: '[class="button-container visible-xs"] > [data-testid=btn-pymt-apply-card]',
    btnPymtProceedToReview: '[data-testid=btn-proceed-to-review]',
    pymtCVVCode: '[class="ccv"]',
    pymtVisaCard: '[class="input-md applied-credit-card-credit-card-number input-validation-valid Visa"]',
    pymtMasterCard: '[class="input-md applied-credit-card-credit-card-number input-validation-valid MasterCard"]',
    pymtAmericanExpCard: '[class="input-md applied-credit-card-credit-card-number input-validation-valid AmericanExpress"]',
    pymtCVV3Code: '[alt="credit card with 3 digit credit card verification number"]',
    pymtCVV4Code: '[alt="credit card with 4 digit credit card verification number"]',
    btnHaveAPromotionCodePlus: '[data-testid=plus-minus-icon]', // '.plus-minus ' > 'div:has-text("Have a Promotion Code?")' > '.plus-minus-icon',
    lblPromotionCode: '[data-testid=lbl-promotion-code]',
    txtPromoCode: '#txtPromoCode',
    promoCodeErrorMsg: '//*[@id="divAddPromoCode"]//*[@id="promo-error-message"]',
    btnPromoCodeApply: '#applyPromo',
    promoCodeSuccessMsg: '#promo-discount-message',
    hdrHaveAGiftCard: '.plus-minus > div:has-text("Have a Gift Card?")',
    btnHaveAGiftCardPlus: '(//*[@class="a11y-drawer-toggle"]//*[@class="plus-minus-icon"])[2]',
    txtYouWillBeEnter: '#gift-card-sub-title',
    lblGiftCard: '[data-testid=lbl-gift-card]',
    lblGiftCardPin: '[data-testid=lbl-pin-number]',
    txtGiftCard: '#txtGiftCard',
    giftCardAppliedAmt: '#applied-amount',
    giftCardRemainingAmt: '#remaining-balance',
    appliedGiftCard: '//span[@class="applied-value input-md"]',
    appliedSuccessMsg: '#gift-card-discount-message',
    removeGiftCardBtn: '//button[@title="Remove Gift Card"]',
    giftCardErrorMsg: '//*[@id="gift-card-accordion"]//*[@id="gift-card-error-message"]',
    giftCardPinErrorMsg: '//*[@id="gift-card-accordion"]//*[@id="pin-error-message"]',
    txtGiftCardPin: '#txtPin',
    btnGiftCardApply: '[data-testid=btn-gift-card-apply]',
    hdrHaveATenderCode: '[data-testid=plus-minus-icon]',
    btnHaveATenderCodePlus: '(//*[@class="a11y-drawer-toggle"]//*[@class="plus-minus-icon"])[3]',
    TxtYouWillBeTenderCode: '#gift-card-sub-title',
    lblTenderCode: '[data-testid=lbl-tender-code]',
    txtTenderCode: '#txtTenderCode',
    tenderCodeSuccessmsg: '[id="gift-card-discount-message"]',
    tenderCodeErrormsg: '//*[@id="tender-code-accordion"]//*[@id="gift-card-error-message"]',
    btnTenderCodeApply: '[data-testid=btn-tender-card-apply]',
    txtPleaseNote: '#gift-card-sub-title',
    verifyCardNumber: '[data-testid=card-number]',
    verifyCardExpiryDate: '[data-testid=verify-card-expiry-date]',
    txtVerifyCardNumber: '#txtVerifyCard]',
    txtVerifySecurityCode: '#security-code-input-undefined',
    btnVerifyApply: '#applyVerifyCard',
    verifyBillingAddress: '[class="col-xs-12 address-display"]',
    lnkBilligAddressEdit: '[class="button button-transparent underlined-link"]',
    lnkChangeCard: '[class="button-transparent edit-credit-card-button"]',
    billingAddrName: '.name',
    billingAddress: '.address text-transform-none',
    billingAddrPhone: '.phone',
    rewardTitle: '//*[@class="col-xs-12 payment-section bottom-section"]//*[@class="section-title"]',
    rewardTitleTooltip: '//*[@class="col-xs-12 payment-section bottom-section"]//*[@class="tooltip-help-wrap payment-panel"]',
    rewardDescription: '//*[@id="reward-sub-title"]/p',
    rewardSubTitle: '.reward-details-title',
    rewardSubTitleTxt: '.reward-details-title-total',
    redeemRewardCardDetails: '(//*[@class="reward-certificate-reward-container"]//*[@class="reward-certificate-reward-number"])[1]',
    redeemRewardCardAllDetails: '(//*[@class="reward-certificate-reward-container"]//*[@class="reward-certificate-reward-number"])',
    redeemRewardCardApplyButton: '(//*[@class="reward-certificate-reward-state"]//button)[1]',
    redeemRewardCardAllApplyButton: '.reward-certificate-reward-state > button',
    rewardAppliedState: '(//*[@class="reward-certificate-reward-container"]//*[@class="reward-certificate-reward-applied"])[1]',
    rewardAppliedStateRemove: '(//*[@class="reward-certificate-reward-container"]//*[@class="a11y-link button-transparent"])[1]',
    totalRewardCertificatesAmount: '.reward-details-title-total-amount',
    redeemRewardsPlusIcon: '(//*[@class="a11y-drawer-toggle"]//*[@class="plus-minus "])[4]',
    enterRewardLink: '//*[@class="button-transparent reward-details-enter-reward"]',
    rewardCertificateNoTxt: '#txtRewardCode',
    redeemRewardApplybutton: '//*[@id="reward-accordion"]//*[@class="button button-primary button-md button-apply"]',
    redeemRewardApplyPromoButton: '//*[@id="reward-accordion"]//*[@class="button button-secondary button-md button-apply-promo"]',
    billingEdit: '[data-testid="lnk-billig-address-edit"]',
    billingContainer: '#popup-content',
    billingPopupSave: '//*[@class="button button-lg button-primary button-next"]',
    chkTaxExemption: 'label[for="tax-exemption"]',
    msgTaxExemptionIneligible: '.tax-exemption-ineligible-state',
    lnkTaxExemptionIneligible: '.tax-exemption-ineligible-state > .a11y-link',
    containerTaxExemption: 'div.taxexempt',
    lblAltPayments: 'label.other-payment-label',
    altPaymentsWrap: 'div.alt-payment-card-icons-wrap',
    txtAppliedPromoCode: '.promo-code-form span.applied-value',
    lblInternationalBillingAddressButton: '[data-testid=btn-international-billing-address]',
    txtBillingFirstName: '#FirstName',
    txtBillingLastName: '#LastName',
    txtBillingAddress1: '#Address1',
    txtBillingZipCode: '#ZipCode',
    txtBillingCity: '#City',
    txtBillingState: '#State',
    txtBillingPhone: '#DaytimePhone',
    txtBillingCountry: '#Country',
    btnChangeCard: '[data-testid=btn-change-card]',
    plccOffer: '[class="plcc-offer-choice"]',
    plccOfferBtn: '[class="button button-md button-primary btn-delivery-continue"]'
  },
  changeCard: {
    hdrApplyNewCard: '[data-testid=hdr-apply-new-card]',
    cardLimitNote: '#card-limit-note',
    listOfCards: '[data-testid=cards-list-item]',
    selectCard1: '//ul[data-testid=cards-list]//li[1]/*[@id="saved-card-0"]',
    btnApplyNewCard: '[class="button-transparent add-new-card-button"]',
    btnUpdatePayment: '#applyCard'
  },
  reviewPage: {
    lblReviewItemGRLabel: '[data-testid=registry-item]',
    lblReviewItemSkuNum: '[data-testid=lbl-review-item-sku-num]',
    lblReviewItemSkuTitle: '[data-testid=item-title]',
    lblReviewItemSkuQty: '[data-testid=lbl-review-item-sku-qty]',
    lblReviewItemSkuPrice: '[data-testid=lbl-review-item-sku-price]',
    lblReviewItemSkuPriceTotal: '[data-testid=lbl-review-item-sku-price-total]',
    lblReviewItemAvailabilityMsg: '[data-testid=lbl-review-item-availability-msg-container]',
    lblReviewItemArrivesByMsg: '[data-testid=lbl-review-item-arrives-by-msg-container]',
    eleRecipientSection: '[data-testid=ele-recipient-section]',
    eleArrayItemList: '[data-testid=ele-array-item-list]',
    eleItemInfo: '[data-testid=ele-item-info]',
    eleShippingMethodSection: '[data-testid=ele-shipping-method-section]',
    eleShippingMethodSectionTop: '[data-testid=ele-shipping-method-section-top]',
    lblSelectedShipMode: '[data-testid=ship-method-default]',
    eleOrderSummary: '[data-testid=summary-list]',
    lblRecipientHeader: '[data-testid=lbl-recipient-header]',
    lblReviewPageGreeting: '[data-testid=lbl-review-page-greeting]',
    lblShipToSingleRecipientHdr: '[data-testid=lbl-shipping-method-to]',
    lblShipToMultiRecipientHdr: '[data-testid=lbl-ship-to-multi-recipient-hdr]',
    lnkShipToRecipientEdit: '[data-testid=lnk-ship-to-recipient-edit]',
    txtRecipientItemHdr: '[data-testid=txt-recipient-item-hdr]',
    lnkRecipientItemEdit: '[data-testid=lnk-recipient-item-edit]',
    imgItem: '[data-testid=review-item-image]',
    lblPolicyUpdate: '.policy-update',
    lnkTermsOfUse: 'a >> nth=0',
    lnkPrivacyPolicy: 'a >> nth=1',
    elePaymentSection: '[data-testid=lbl-payment-section-title]',
    lblTax: '',
    lblPaymentInfoReward: '[data-testid=lbl-payment-info]',
    REVIEW_SHIP_BLOCK: '[data-testid=review-ship-block]',
    btnPlaceOrder: '[data-testid=button-place-order], [data-testid=btn-proceed-to-place-order]',
    lnkContactInfo: '[data-testid=lnk-contact-info]',
    lnkEditGiftOptions: '[data-testid=lnk-edit-gift-options]',
    lblGiftOptionsMsg: '[data-testid="lbl-gift-options-message"]',
    lnkEditShippingMethod: '[data-testid=lnk-edit-shipping-method]',
    lblRecipientArrivesMsg: '[data-testid=lbl-recipient-arrives-msg]',
    eleGiftingSection: '[data-testid=ele-gifting-section]',
    eleContactInfo: '[data-testid=ele-contact-info]',
    lblShippingSectionHeader: '[data-testid=lbl-shipping-method-hdr]',
    lblGiftingSectionHeader: '[data-testid=lbl-gifting-section-hdr]',
    lblContactSectionHeader: '[data-testid=lbl-contact-section-header]',
    lnkShippingSectionEdit: '[data-testid=lnk-shipping-section-edit]',
    lnkGiftingSectionEdit: '[data-testid=lnk-gifting-section-edit]',
    lnkContactSectionEdit: '[data-testid=lnk-contact-section-edit]',
    lblRecipientEmail: '[data-testid=lbl-recipient-email]',
    eleReviewPaymentBlock: '[data-testid=ele-payment-info]',
    lblPaymentInfo: '[data-testid=lbl-payment-info]',
    eleBillToAddress: '[data-testid=ele-bill-to-address]',
    lblBillToAddress: '[data-testid=review-ship-block]',
    lnkEditPayment: '[data-testid=lnk-edit-payment]',
    rewardInfo: '[class="rewards-exceeded-order-total"]',
    divTym: '.tym-wrapper',
    lblTymTitle: 'h3.tym-title',
    lblTymCopy: 'p.tym-copy',
    rdTymOption1: 'input#tym_undefined_1',
    rdTymOption2: 'input#tym_undefined_2',
    lblTymOption1: 'label[for="tym_undefined_1"]',
    lblTymOption2: 'label[for="tym_undefined_2"]',
    lblTymAddress: 'div#tym-address-wrap',
    lblRegistryItem: '[data-testid="registry-item"]'
  },
  confirmationPage: {
    lblOrderConfirmationDtl: '[data-testid=lbl-order-confirmation-dtl] > :nth-child(1)',
    lblConfirmationMsg: '[data-testid=lbl-confirmation-msg]',
    lblOrderNumber: '[data-testid=lbl-order-number]',
    lblOrderDate: '[data-testid=lbl-order-date]',
    lblOrderTotal: '[data-testid=lbl-order-total]',
    eleRecipientSection: '[data-testid=receiptSummary]',
    eleRecipientChild: '#receiptSummary > div',
    eleRecipientCount: '[data-testid=el-recipient-count]',
    eleShippingAddress: '[data-testid=ele-shipping-address]',
    eleBillingAddress: '[data-testid=ele-billing-address] >> [data-testid=bill-to-address]',
    lnkPrintReceipt: '[data-testid=lnk-print-receipt]',
    lnkViewOrderDetails: '[data-testid=confirmation-header-view-order]',
    lblRecipientEmail: '[data-testid=lbl-recipient-email]',
    btnPrintDialogCancel: '.cancel-button',
    shipToName: '[data-testid=ship-to-name]',
    shipToAddress: '[data-testid=ship-to-address]',
    shipToPhone: '[data-testid=ship-to-phone]',
    billToName: '[data-testid=bill-to-name]',
    billToAddress: '[data-testid=bill-to-address]',
    billToPhone: '[data-testid=bill-to-phone]',
    lblPaymentInfo: '[data-testid=lbl-payment-info]',
    lblItemListHdr: '[data-testid=lbl-item-list-hdr]',
    eleItemList: '[data-testid=ele-item-list]',
    imgProduct: '[data-testid=img-product]',
    lblProductTitle: '[data-testid=lbl-product-title]',
    lblSkuPrice: '[data-testid=lbl-sku-price]',
    lblAvailabilityMsg: '[data-testid=lbl-availability-msg] > span',
    lblArrivesByMessage: '[data-testid=lbl-arrives-by-message]',
    lblBackOrderArrivesByMessage: '[data-testid=lbl-backorder-arrives-by-message]',
    lblSkuQty: '[data-testid=lbl-sku-qty]',
    lblPriceTotal: '[data-testid=lbl-price-total]',
    personalizationDetails: '[class="personalization-design-info"]',
    lblRecipientAvailabilityMsg: '.product-arrives-by-message.shipment-message, .shipment-message',
    lblMerchadiseTotalAmount: '[data-testid=confirmation-order-summary-merchandise-subtotal]',
    lblShippingHandlingAmount: '[data-testid=confirmation-order-summary-shipping-subtotal]',
    lblShippingDiscountAmount: '[data-testid=confirmation-order-summary-shipping-discount]',
    lblTaxTotalAmount: '[data-testid=confirmation-order-summary-tax-total]',
    lblSummaryTotalAmount: '[data-testid=confirmation-order-summary-total-charge]',
    lblGiftCardAmount: '[data-testid=confirmation-order-summary-gift-card-amount]',
    lblGiftBoxAmount: '[data-testid=confirmation-order-summary-gift-box-subtotal]',
    lblRemainingAmount: '[data-testid=confirmation-order-summary-total-due]',
    paymentCardInfo: '[class="credit-card-digits"]',
    paymentCardListInfo: '[class="credit-card-digits"]',
    lblRewards: '[data-testid=confirmation-order-summary-tender-card-amount]',
    divRegistryItem: '[data-testid="registry-item"]'
  },
  txtLocators: {
    // txtDtpCanBeApplied: 'Tax exemption can be applied during checkout.'
    txtDtpCanBeApplied: 'Trade Program discount has been applied.'
  },
  giftRegistryItems: {
    lnkViewRegistry: '[data-testid=lnk-view-registry]',
    lblShippingAddressMessageGiftRegistry: '[data-testid=shipping-address-message-gift-registry]',
    lblShipToGrAddressMessageEdit: '[data-testid=ship-to-gr-address-message-edit]',
    lblShipToGrAddressMessageReview: '[data-testid=ship-to-gr-address-message-review]',
    lblRegistryItem: '[data-testid=registry-item]',
    lblShipToGrAddress: '[data-testid=ship-to-gr-address]',
    lblShipToGrAddressMessage: '[data-testid=ship-to-gr-address-message]',
    lblShipToGrAddressMessageConfirm: '[data-testid=ship-to-gr-address-message-confirm]',
    btnSharedRegistryPopupClose: '#popup-close'
  },
  freeShippingPopup: {
    hdrFreeShippingPopup: '[class="crate-helvetica-roman cmsBlack promoHead"]',
    hdrSubFreeShippingPopup: '[class*="pop-sub"]',
    msgFreeShippingPopup: '[class="crate-helvetica-roman tAndC"]',
    hdrCB2FreeShippingPopup: '[class="free-shipping-cms-popup"] > h1',
    hdrCB2SubFreeShippingPopup: '[class="free-shipping-cms-popup"] > h2',
    msgCB2FreeShippingPopup: '[class="cb2-brown-light"]'
  }
};
