module.exports = {
  homePage: {
    lnkHamburgerMenu: 'button.header-menu-toggle',
    lnkOrderOrSignin: '[class="account-link"]',
    lnkSignInHeader: 'button.login-popup-button',
    lnkAcntHeader: "(//*[name()='svg'][@aria-label='Account'])[1]",
    lnkSignOut: 'div#flyout-header-account > ul > li > button',
    lnkOrderTracking: "//a[text()='Orders']",
    lnkTrackOrder: "//a[normalize-space()='Track Orders / Schedule Delivery']",
    btnAccountIconMobile: 'button[class*=account-icon-link]',
    lnkTrackOrderMobile: '.account-flyout-menu > li:nth-of-type(2) > a',
    lnkFavoritesMobile: '.account-flyout-menu > li:nth-of-type(4) > a',
    btnAccountIcon: "[data-testid*='header-account-container']",
    btnAccountMobile: "[class*='account-login-button']",
    lnkSignInMobile: "//button[contains(@class,'account-menu-signin')]",
    lblHeaderLoginNameCB2: '.header-account-greeting',
    btnFlyoutCloseMobile: "div#flyout-header-account button[class*='button-flyout-close']",
    lnkOrderTrackingCB2: "//a[contains(text(),'Track Orders')]",
    lnkHomePageLogo: '.header-logo-container > a:nth-of-type(1)',
    lblAcntName: "[data-testid='header-account-link']",
    svgAccountIcon: 'div.account-link-container',
    lnkMyAccount: "//a[normalize-space()='My Account']",
    lnkRewardsFlyout: "//div[@id='header-account']//a[@href='/account/rewards/']",
    lblAcntGreeting: '[data-testid="header-account-link"]',
    lblAcntGreetinCB2: 'p.header-account-greeting'
  },

  SECONDARY_CATEGORY: {
    CrateWeddingRegistry: "//a[@id='Nav_Wedding-Registry']",
    FreeDesignServices: "//a[@id='Nav_Free-Design-Services']",
    TradeProgram: "//a[@id='Nav_Trade-Program']",
    Collborations: "//a[contains(@id,'Nav_Collaborations')]",
    Instock: "///button[contains(.,'In-Stock')]",
    BlackFridayDeals: "//a[@id='Nav_Black-Friday-Deals']",
    ThanksGiving: "//a[@id='Nav_Thanksgiving']",
    Christmas: "//a[@id='Nav_Christmas']",
    KidsBabyRegistry: "//a[@id='Nav_Baby-Registry_kids']",
    KidsFreeDesignServices: "//a[@id='Nav_Free-Design-Services_kids']",
    KidsTradeProgram: "//a[@id='Nav_Trade-Program_kids']",
    KidsCollaborations: "//a[@id='Nav_Collaborations_kids']",
    KidsInStock: "//button[contains(@aria-controls,'Flyout_In-Stock_kids')]",
    KidsChristmas: "//a[@id='Nav_Christmas_kids']",
    KidsBlackFridayDeals: "//a[@id='Nav_Black-Friday-Deals_kids']"
  },

  loginPage: {
    txtEmail: '#okta-signin-username',
    txtPassword: '#okta-signin-password',
    btnSignIn: '#okta-signin-submit',
    msgLoginError: '#form1 > div.o-form-content.o-form-theme.clearfix > div.o-form-error-container.o-form-has-errors > div > div > p',
    btnSignInWithApple: '[class="social-auth-button social-auth-apple-button link-button default-custom-button"]',
    btnSignInWithGoogle: '[class="social-auth-button social-auth-google-button link-button default-custom-button"]',
    lnkResetPassword: '#forgot-password',
    btnCreateAccount: '//a[text()="Create Account"]',
    lnkTermsOfUse: '//*[@id="sign-in-agreement-msg"]/a[1]',
    lnkPrivacyPolicy: '//*[@id="sign-in-agreement-msg"]/a[2]',
    lnkTrackOrder: '//div[contains(@class,"login-order-tracking")]/a[1]',
    hdrSignInForm: '.form-sign-in-title',
    lblEmail: '//label[@for="okta-signin-username"]',
    lblPassword: '//label[@for="okta-signin-password"]',
    msgAgreement: '#sign-in-agreement-msg',
    hdrCreateAccount: '.page-title',
    msgAccountList1: '//li[@class="account-list-item"][1]',
    msgAccountList2: '//li[@class="account-list-item"][2]',
    msgAccountList3: '//li[@class="account-list-item"][3]',
    msgAccountList4: '//li[@class="account-list-item"][4]',
    msgAccountList5: '//li[@class="account-list-item"][5]',
    msgAccountList6: '//li[@class="account-list-item"][6]',
    msgAccountList7: '//li[@class="account-list-item"][7]',
    hdrResetPasswordPopup: '.forgot-password-title',
    msgResetPasswordPopup: '.forgot-password-msg',
    lblEmailResetPasswordPopup: '//label[@for="ForgotPasswordEmailAddress"]',
    txtEmailResetPasswordPopup: '#ForgotPasswordEmailAddress',
    btnCancelResetPasswordPopup: 'button[class*="button-forgot-password"] >> nth=0',
    btnSubmitResetPasswordPopup: 'button[class*="button-submit button-forgot-password"]',
    btnCloseResetPasswordPopup: '#popup-close',
    msgSuccessResetPasswordPopup: '.success'
  },

  registryPage: {
    lnkManageRegistry: 'div[class*="manage-registry-block"] a',
    lnkManageRegistryCB: 'div.gr-hero-copy > a',
    lnkManageRegistryCBMobile: 'a[class="manage-link gr-cms-manage-link"]',
    lnkManageRegistryCB2Mobile: 'button#second-mobile-manage-registry-trigger-link',
    lnkManageRegistryMobile: '#mobile-manage-registry-trigger-link',
    lnkCreateRegistry: '[data-testid="registries-list-create-registry"]',
    lnkCreateMyRegistryCB: '#createRegistryBtn',
    lnkCreateMyRegistryCBmob: '#Nav_Nav_CreateRegistry',
    lnkCreateMyRegistryCB2: '#create-my-registry-button',
    lnkCreateMyRegistryCB2mob: "a[data-name='Nav-Nav-Create_A_Registry']",
    txtGiftRegistry: '.create-registry-small-title',
    txtLetsGetYouRegistered: '.create-registry-large-title',
    lblFName: "label[for='gr-firstName']",
    lblLName: "label[for='gr-lastName']",
    lblPhone: "label[for='gr-phone']",
    lblEmail: "label[for='gr-email']",
    lblRegistryType: "label[for='gr-registryType']",
    drpRegistryType: '#gr-registryType',
    txtFName: '#gr-firstName',
    txtLName: '#gr-lastName',
    txtPhone: '#gr-phone',
    txtEmail: '#gr-email',
    btnContinue: "//span[normalize-space()='Continue']",
    lnkPrevious: '#registration-previous-button',
    txtCreateAcntH1: "div[class='form-titles step-create-account-form-titles'] h1",
    txtCreateAcntH2: "div[class='form-titles step-create-account-form-titles'] p",
    lblCreatePassword: "label[for='StrongPassword']",
    txtCreatePassword: "//input[@id='StrongPassword'] | //input[@id='okta-signin-password']",
    btnCreateAcnt: "//button[@id='gr-step-create-account-button'] | //input[@id='okta-signin-submit']",
    btnPrevious: '#registration-previous-button',
    lnkPreviousEx:
      "//button[@class='dsButton_1r2-k dsButtonSecondary_1B2l5 dsButtonLg_1Sq4t button-sm gift-registry-previous-button'] | //button[@class='dsButton_3rImP dsButtonSecondary_ex3CB dsButtonLg_2fphl button-sm gift-registry-previous-button']",
    txtPolicy: '.terms-and-conditions-text',
    txtwelcomeMsg: '.header-account-link',
    lblAcntGreetinCB2: '#header-account',
    txtWelcomeBack: "h2[class='promote-sign-in-title form-sign-in-title design-services-title'] p",
    txtReturningCustomerEmail: "//input[@id='okta-signin-username']",
    lnkResetPassword: '#forgot-password',
    btnSignInWithApple: "//a[normalize-space()='Sign in with Apple']",
    btnSignInWithGoogle: "//a[normalize-space()='Sign in with Google']",
    lnkFirstRegistry: '[data-testid="registries-list-registries"] > div:nth-of-type(1) a',
    btnBrandSwitch: '#brand-switch',
    lnkSisterBrand: 'div[class*="control"] a'
  },

  createAccountPage: {
    lblAcntHeader: "//h1[contains(@class,'page-title')]",
    lblAcntDesc: "//p[contains(@class,'account-description')]",
    btnAppleLogin: "//button[contains(@class,'apple-create-account')]",
    btnGoogleLogin: "//button[contains(@class,'g-signin')]",
    lblFirstName: "//label[@for='firstName']",
    txtFirstName: '#firstName',
    lblLastName: "//label[@for='lastName']",
    txtLastName: '#lastName',
    lblEmail: "//label[@for='email']",
    txtEmail: '#email',
    lblPhone: "//label[@for='phone']",
    txtPhone: '#phone',
    lblPassword: "//label[@for='StrongPassword']",
    txtPassword: '#StrongPassword',
    btnCreateAccount: "//button[contains(@class,'button button-primary')] | //input[contains(@class,'button button-primary')]",
    lblPolicy: '#sign-in-agreement-msg',
    btnShowPassword: "//button[@class='button-transprent password-show']",
    lblPasswordReq1: '#PasswordSuccessCriteriaInfo > ul > li:nth-of-type(1)',
    lblPasswordReq2: '#PasswordSuccessCriteriaInfo > ul > li:nth-of-type(2)',
    lblPasswordReq3: '#PasswordSuccessCriteriaInfo > ul > li:nth-of-type(3)',
    lblPasswordReq4: '#PasswordSuccessCriteriaInfo > ul > li:nth-of-type(4)',
    lblPasswordReq5: '#PasswordSuccessCriteriaInfo > ul > li:nth-of-type(5)'
  },

  accountPage: {
    lblUsername: "[data-testid *='salutation']",
    lblUsernameInHeader: '.account-link',
    lblCB2UsernameInHeader: '.header-account-greeting',
    lnkAccountSettings: "//a[text()='Account Settings'] | //a[text()='account settings']",
    lnkAccountSettingsMobile: "//div[@class='left-nav-items']//a[text()='Account Settings'] | //div[@class='left-nav-items']//a[text()='account settings']",
    btnAddress: "//button[text()='Addresses'] | //button[text()='addresses']",
    lnkAddresses: "//button[normalize-space()='addresses'] | //button[normalize-space()='Addresses']",
    btnAddressMobile: "//div[@class='left-nav-items']//button[text()='Addresses'] | //div[@class='left-nav-items']//button[text()='addresses']",
    lnkPayments: "//a[text()='Payments']  | //a[text()='payments']",
    lnkPaymentsMobile: "//div[@class='left-nav-items']//a[text()='Payments']  | //div[@class='left-nav-items']//a[text()='payments']",
    lnkAddNewPayment: "//button[contains(@class,'add-card-btn')]",
    lblAccountSettingsEmail: '#accountEmail_current',
    txtAccountSettingsEmail: '#accountEmail',
    lnkSignOut: "//div[@class='order-nav-name']//a[text()='sign out'] | //div[@class='left-nav-items']//button[text()='Sign Out']",
    lnkSignOutMobile: "//div[@class='left-nav-items']//a[text()='sign out'] | //div[@class='left-nav-items']//button[text()='Sign Out']",
    lnkMyFavorites: 'a:has-text("My Favorites") >> visible=true >> nth=0',
    btnADDRESSES_BTN: "//button[text()='Addresses']",
    btnMyAccount: "//button[contains(@class,'my-account-menu-toggle')]",
    lnkDesignPackage: 'a:has-text("Design Packages") >> visible=true >> nth=0',
    lnkRewards: "//div[@class='left-nav-items']//a[text()='Rewards']",
    btnPreferences:
      "//div[@class='left-nav-items']//button[text()='Preferences/Subscriptions'] | //div[@class='left-nav-items']//button[text()='preferences/subscriptions']",
    lnkCatalogSubscriptions:
      "//div[@class='left-nav-items']//span[text()='Catalog Subscriptions'] | //div[@class='left-nav-items']//span[text()='catalog subscriptions']",
    lnkMyStoreCrate: 'div.left-nav-items li:nth-of-type(9) a',
    lnkMyStoreCB2: 'div.left-nav-items li:nth-of-type(8) a',
    lnkMyStoreCrateCA: 'div.left-nav-items li:nth-of-type(8) a',
    lnkMyStoreCB2CA: 'div.left-nav-items li:nth-of-type(7) a',
    lnkMyStoreMobile: "//div[@class='left-nav-items']//a[contains(text(),'My Store')] | //div[@class='left-nav-items']//a[contains(text(),'my store')]",
    lnkCustomerService: "//div[@class='left-nav-items']//a[text()='customer service'] | //div[@class='left-nav-items']//a[text()='Customer Service']",
    lnkEmailPreferences: 'div[id*="references"] a[href*="communication-preferences"]',
    lnkEmailPreferencesMobile: '//div[@class="left-nav-items"]//div[contains(@id,"references")]//a[contains(@href,"communication-preferences")]',
    lnkManageCBCC: "//div[@class='left-nav-items']//a[contains(text(),'Manage Crate & Barrel Credit Card')] | (//a[contains(text(),'cb2 credit card')])[1]"
  },

  addPayment: {
    btnAddNewCard: "//button[contains(@class,'add-card-btn')]",
    // btnAddNewCard: 'div.cards-container button',
    mdlAddPayment: '#popup-content .payment-info-form',
    lblAddPaymentHeader: '.add-card-title',
    lblAddPaymentCCNum: "//label[contains(@for,'CreditCardNum')]",
    lblAddPaymentExpDate: "//label[contains(@for,'expiration-date')]",
    lblAddPaymentSecCode: "//label[contains(@for,'security-code')]",
    lblAddPaymentPrimary: '.save-card-to-account',
    chkAddPaymentPrimary: "//label[contains(@for,'AppliedCreditCard_IsPrimary')]",
    btnAddPaymentCancel: '#cancelCard',
    btnAddPayment: "//div[contains(@class,'button-container')][1]//button[2]",
    btnAddPaymentMobile: "//div[contains(@class,'button-container')][2]//button[1]",
    txtAddPaymentCCNum: "//input[contains(@class,'applied-credit-card-credit-card-number')]",
    txtAddPaymentExpDate: "//input[contains(@class,'credit-card-expiration-date')]",
    txtAddPaymentSecCode: "//input[contains(@class,'security-code')]",
    imgAddPaymentVisa: "//div[@class='card-image Visa']",
    imgAddPaymentMaster: "//div[@class='card-image MasterCard']",
    imgAddPaymentDiscover: "//div[@class='card-image Discover']",
    imgAddPaymentAmex: "//div[@class='card-image AmericanExpress']",
    imgAddPaymentPLCC: "//div[@class='card-image PLCCSynchrony']",
    imgAddPaymentCBCC: "//div[@class='card-image CoBrandMasterCard']",
    lblAddedCCNum: "//div[contains(@class,'card-primary-container')]//div[@class='card-number']",
    lblAddedExp: "//div[contains(@class,'card-primary-container')]//*[@class='expiration-date']",
    lblAddedPaymentDefault: "//div[contains(@class,'card-primary-container')]//div[@class='default-payment-container']",
    svgAddedPaymentDel: "//div[contains(@class,'card-primary-container')]//div[@class='card-delete-container']/button",
    svgAddPaymentDefault: "//*[contains(@class,'default-checkmark')]",
    btnDeleteCC: "(//button[contains(@class,'card-delete-btn')])",
    btnCCDeleteConfirm: "(//button[text()='Yes, Delete'])[1]",
    btnCCDeleteConfirmMobile: "(//button[text()='Yes, Delete'])[2]"
  },

  addAddress: {
    lnkShippingAddress: "//div[@class='left-nav-items']//div[@id='Addresses']//a[1] | //div[@class='left-nav-items']//div[@id='addresses']//a[1]",
    lnkAddBilling: "//div[@class='left-nav-items']//div[@id='Addresses']//a[2] | //div[@class='left-nav-items']//div[@id='addresses']//a[2]",
    btnAddNewAddress: "//button[text()='+ Add New Address']",
    lblAddShippingAddressHeader: "//h1[text()='Add Shipping Address']",
    lblAddShippingAddressFname: "//label[@for='ba-firstName']",
    txtAddShippingAddressFname: '#ba-firstName',
    lblAddShippingAddressLname: "//label[@for='ba-lastName']",
    txtAddShippingAddressLname: '#ba-lastName',
    lblAddShippingAddress: "label[for='ba-address1']",
    txtAddShippingAddress: '#ba-address1',
    lblIntBillingAddress: "//label[@for='ba-address1-2']",
    txtIntBillingAddress: '#ba-address1',
    lnkAddShippingApt: "//button[contains(@class,'extended-address')]",
    lblAddShippingApt: "//label[@for='ba-address2']",
    txtAddShippingApt: '#ba-address2',
    txtAddShippingAddress3: '#ba-address3',
    lblAddShippingZipcode: "//label[@for='ba-zipCode']",
    txtAddShippingZipcode: '#ba-zipCode',
    lblAddShippingCity: "//label[@for='ba-city']",
    txtAddShippingCity: '#ba-city',
    lblAddShippingState: "//label[@for='sel-state']",
    lblIntBillingState: "//label[@for='ba-state-2']",
    txtIntBillingState: '#ba-state-2',
    drpAddShippingState: '#sel-state',
    lblAddShippingPhone: "//label[@for='ba-daytimePhone']",
    txtAddShippingPhone: '#ba-daytimePhone',
    btnAddShippingAddress: '#ba-Submit',
    mdlAddShippingCheck: '.confirm-dialog',
    btnAddShippingKeepAddress: "//button[contains(@class,'btn-keep-address')]",
    cntAddShippingName: "//div[@class='account-shipping-addresses-container']/div[2]/div/div[1]",
    cntAddShippingAddressLine: "//div[@class='account-shipping-addresses-container']/div[2]/div/div[2]",
    cntAddShippingCity: "//div[@class='account-shipping-addresses-container']/div[2]/div/div[4]",
    cntAddShippingPhone: "//div[@class='account-shipping-addresses-container']/div[2]/div/div[5]",
    lblBillingAddressHeader: "h1[class*='account-title account-billing-title']",
    lblBillingAddressDomestic: "//label[@for='ba-domestic']",
    radBillingAddressDomestic: '#ba-domestic',
    lblBillingAddressinternational: "//label[@for='ba-international']",
    txtBillingAddressEmail: '#ba-email',
    btnBillingAddress: '#ba-Submit',
    lblBillingAddressUpdated: '#successMessage',
    // lblBillingAddressSuccessMsg: '#successMessage > div[class*=hidden]',
    lblBillingAddressSuccessMsg: '#successMessage',
    radInternational: "//label[@for='ba-international']",
    drpInternationalCountry: '#sel-country',
    lblInternationalEmail: "//label[@for='ba-email']",
    txtInternationalEmail: '#ba-email',
    lblAddress2: "//label[@for='ba-address2']",
    txtAddress2: '#ba-address2',
    lblAddress3: "//label[@for='ba-address3']",
    txtAddress3: '#ba-address3',
    lblDTPBillingAddressMessage: '.avs-margin-top',
    lblDTPBillingAddressTitle: '.section',
    lblDTPBillingAddress: '.readonly-address',
    msgAddressSuccess: '.account-checkmark',
    btnEditShippingAddress: "(//button[normalize-space()='Edit'])[1]",
    btnUpdateAddress: "//button[normalize-space()='Update Address']",
    btnKeepAddressAsEntered: "//div[@id='popup-content']//button[2]",
    btnDeleteAddress: "//button[@class='button button-transparent delete-address-btn']",
    btnYesDeleteAddress: "//button[normalize-space()='yes, delete']",
    btnAptToggle: "button[class*='extended-address-toggle']",
    drpCityInternational: "select[data-testid='sel-state-element']"
  },

  manageRegistry: {
    lblHeader: "//h1[@class='headline-manage-my-registry']",
    cntRegistry: "//div[contains(@class,'jsRegistrySearchResult')]"
  },

  accountSettingsPage: {
    lblAccountSettingsheader: "//h1[contains(@class,'account-settings-title')]",
    lblUpdateEmail: 'text=Update Email',
    lblUpdatePassword: 'text=Update Password',
    lblCurrentEmailLabel: '#accountEmailLabel',
    lblCurrentEmail: '#accountEmail_current',
    msgUpdatePassword: "[class='update-password-msg']",
    txtNewEmail: '#accountEmail',
    txtConfirmEmail: '#confirmEmail',
    btnApplyChangesEmail: '[class="edit-signin update-email col-xs-12 col-sm-5"] >> text=Apply Changes',
    txtOriginalPassword: '#StrongOriginalPassword',
    txtNewPassword: '#StrongPassword',
    btnApplyChangesPassword: '[class="edit-signin update-password col-xs-12 col-sm-5 "] >> text=Apply Changes',
    msgUpdateSummary: "//div[@class='update-password-summary']",
    msgEmailUpdated: '#accountEmailAcceptance',
    msgPasswordUpdated: "[class*='edit-signin update-password'] >> [class*='success-cofirmation']",
    lblUpdatePasswordDTP: '.update-password-msg',
    lblDTPEmailMsg: '[class*=current-email]',
    lblOriginalPassword: '[for=StrongOriginalPassword]',
    lblNewPassword: '[for=StrongPassword]',
    btnApplyChangesPassworDTP: "//button[text()='Apply Changes']"
  },

  myFavoritesPage: {
    msgEmptyFavoritesPage: "[class='cb-mb-lp__content__header renew__large crate-bold']",
    msgEmptyFavoritesPage1: '[class="crate-roman crate-serif renew__body--reg"] >> text=Already have favorites?',
    lblFavoriteItemCount: '.user-favorites-count',
    lblMyFavoritesTitle: "//h1[text()='My Favorites']",
    imgNoItem: '.no-items-img',
    lnkMakeCopy: '#js-make-copy',
    lnkSignOut: 'a.mb-sign-in',
    btnMoodBoard: '#jsMakeMoodBoard',
    msgBanner: '[class="favorites-layout-text"]',
    skutitle: '//h4[@class="productTitle"]',
    skuNum: '.favorite-sku',
    btnRemoveItem: 'button[class*="delete-item"]',
    btnAddToCart: '[data-id=addToCartButton]',
    btnAddToRegistry: '#addToregistryButton',
    txtQuantity: '.qty-input',
    btnAddToAnotherList: '.button-transparent add-list',
    arrayFavoriteItemElements: '[class="row favorites-list-row"]',
    skuPrice: '[class=regPrice]',
    msgNoItemCb2: '.section-tag-line',
    popupGeoLocation: '[data-id="popup-container"]',
    btnContinueToCanadaSite: '//button[text()="Continue to Canadian Site"]',
    btnFavorites: 'button[title="Save to Favorites"]',
    divFavoritesCount: 'ul[class*="line-item-list"] li'
  },

  orderTrackingPage: {
    txtOrderNum: '#orderNumber',
    txtEmail: '#email',
    btnViewOrder: '.order-tracking-button > button'
  },

  orderDetails: {
    lblMerchandiseAmount: "li[class*='merchandise-row'] > .amount",
    lblShippingAmount: "li[class*='shipping-row'] > .amount",
    lblTax: "li[class*='tax-row'] > .amount",
    lblOrderTotal: "li[class*='orderTotal'] > .amount",
    lblOrderTotalMobile: "li[class*='grand-total'] > .amount",
    lblGreetingMsg: 'div.okta-sign-in-top h2',
    lnkResetPassword: '#forgot-password',
    lblPrivacyPolicy: '//*[@id="sign-in-agreement-msg"]',
    lblPromotionTxt: 'div.promote-sign-in-text'
  },

  cartPage: {
    lnkCartSignIn: '[data-testid=lbl-cart-sign-in] button',
    btnCartSignInMobile: '[data-testid=lbl-mobile-cart-sign-in] >> [class*=button-sigin]',
    msgCartSignIn: "[data-testid='lbl-cart-sign-in']",
    popupCartLogIn: '.cart-login-container',
    lblEmail: '//label[@for="okta-signin-username"]',
    lblPassword: '//label[@for="okta-signin-password"]',
    txtEmail: '#okta-signin-username',
    txtPassword: '#okta-signin-password',
    btnSignIn: '#okta-signin-submit',
    btnSignInWithApple: '[class="social-auth-button social-auth-apple-button link-button default-custom-button"]',
    btnSignInWithGoogle: '[class="social-auth-button social-auth-google-button link-button default-custom-button"]',
    lnkResetPassword: '#forgot-password',
    msgAgreement: '#sign-in-agreement-msg',
    lnkCreateAccount: '.create-account-link',
    hdrPopUpSignInForm: '[class*=form-sign-in-title]',
    lnkTermsOfUse: '//*[@id="sign-in-agreement-msg"]/a[1]',
    lnkPrivacyPolicy: '//*[@id="sign-in-agreement-msg"]/a[2]',
    mdlChkFlyout: 'div#popup-content > div'
  },

  interrupter: {
    lblOfferbanner: "[data-testid='email-sms-mobile-medium-banner-title']",
    lblOfferBanner2: '[data-testid="email-sms-mobile-medium-banner-text"]',
    lblSMSOnlyOfferBanner: '[data-testid="email-sms-mobile-medium-banner-title"]',
    popInterrupter: '#email-signup-banner-container',
    lblInterrupterBannerMobile: '.email-signup-message-container',
    btnOfferBanner: '.email-signup-message-container > button:nth-of-type(1)',
    btnOfferBannerPhone: "[data-testid='email-sms-mobile-medium-banner-button']",
    btnOfferBannerClose: '.email-signup-message-container > button:nth-of-type(2)',
    btnMaybeLater: '#email-sms-maybe-later-button',
    btnMaybeLaterMobile:
      "//div[@class='mobile-interrupter-body']//div[@class='email-sms-interrupter-form-submit-row']//button[@id='email-sms-maybe-later-button']",
    lblInterrupterHeader: '.email-sms-interrupter-title-text',
    lblInterrupterSubText: '.email-sms-interrupter-form-message',
    lblInterrupterDesc: "[class='email-sms-interrupter-form-footer-row email-sms-terms-above-button']",
    lblInterrutperDescCA: "[data-testid='email-sms-interrupter-form-footer-email']",
    txtInterrupterSMS: "[class='row email-sms-interrupter-field-row'] > input",
    btnInterrupterSubmit: '.email-sms-interrupter-form-fields-group button:nth-of-type(1)',
    lblSecondPageHeader: "[data-testid='email-sms-interrupter-site-select-title']",
    lblSecondPageSubtext: "[data-testid='email-sms-interrupter-site-select-form-message']",
    lblSecondPageDesc: "[data-testid='email-sms-interrupter-site-select-sub-cta']",
    btnSecondPageSubmit: "[data-testid='email-sms-interrupter-site-select-submit']",
    lblInterrupterEmail: "[for='email']",
    lblInterrupterPhone: "[for='cellPhone']",
    lblThanksMsgFinalScreen: '.email-sms-interrupter-thank-you-title',
    lblThanksSubMsgFinalScreen: '.email-sms-interrupter-subscribed-sub-title',
    btnStartShopping: "[data-testid='email-sms-interrupter-thank-you-button']",
    sectionInterrupter: "section[id='global-popup']",
    txtEmail: '#email',
    txtPhone: '#cellPhone',
    lblKidsCheckbox: "label[for='emailadditionalOptIn']",
    chkKidsCheckbox: "[data-testid='email-sms-interrupter-email-kids-field']",
    chkCB2: '#siteSelectCb2',
    chkCrate: '#siteSelectCrateAndBarrel',
    chkCrateandKids: '#siteSelectCrateAndKids',
    chkHG: '#siteSelectHudsonGrace',
    chkBrands: '.site-select-list li',
    chkAdditionalBrands: '.site-select-list li input',
    lblSubTextFinalScreen: '[data-testid="email-sms-interrupter-thank-you-message"]',
    lblMainEmailPhoneAlreadyOptIn: '[data-testid="email-sms-interrupter-thank-you-step"] h2',
    lblSubEmailPhoneAlreadyOptIn: '[data-testid="email-sms-interrupter-thank-you-step"] div',
    lblMainPhoneOnlyAlreadyOptedIn: '[class="email-sms-interrupter-site-select-title-row"] h2',
    lblSubPhoneOnlyAlreadyOptedIn: '[data-testid="email-sms-interrupter-site-select-form-message"]',
    btnSubmitSecondPage: '[data-testid="email-sms-interrupter-site-select-submit"]',
    lblFirstAdditionalBrand: 'li[class="interrupter-select-item"]:nth-of-type(1) label',
    lnkTerms: '[data-testid="email-sms-interrupter-form-footer-combo"] a:nth-of-type(1)',
    lnkPrivacy: '[data-testid="email-sms-interrupter-form-footer-combo"] a:nth-of-type(2)',
    lnkOffers: '[data-testid="email-sms-interrupter-form-footer-combo"] a:nth-of-type(3)',
    btnClaimOfferMobile: '[data-testid="email-sms-mobile-medium-banner-button"]'
  },

  shippingpage: {
    txtReceiptEmail: '#receiptEmail'
  },

  confirmationPage: {
    lblCreateAccount: 'div.create-account-inner-div h2',
    lblCreateAccountDesc: 'div.guest-confirmation-message ul',
    lblEmailHeader: 'div.account-create-email b',
    lblEmailAddress: 'div.account-create-email p',
    lblPassword: 'label.password-label',
    txtPassword: 'input#StrongPassword, input#okta-signin-password',
    lblPasswordReq: 'div#PasswordSuccessCriteriaInfo',
    btnCreateAccount: "div.create-account-inner-div button[class*='button-primary']",
    btnAppleSignin:
      "div.create-account-inner-div button[class*='apple-create-account-button'], button.apple-create-account-button, div.primary-auth-container a:nth-child(2)",
    btnGoogleSignin: "div.create-account-inner-div button[class*='g-signin-btn'], div.customGPlusSignIn, div.primary-auth-container a:nth-child(3)",
    lblDividerText: 'div.auth-divider-text',
    lblConsent: 'div#sign-in-agreement-msg',
    lblCreateAcntSuccess: 'div.confirmation-newaccount-create',
    lnkLogin: "//a[text()='log in']",
    lblLoginHeader: 'div.okta-sign-in-top h2',
    lblLoginDesc: 'div.promote-sign-in-text',
    lblEmail: "label[for='okta-signin-username']",
    lblUserEmail: 'input#okta-signin-username',
    lblPass: "label[for='okta-signin-password']",
    btnSignin: 'input#okta-signin-submit',
    lblAgreement1: "div[class*='sign-in-agreement'] > p:nth-of-type(1)",
    lblAgreement2: "div[class*='sign-in-agreement'] > p:nth-of-type(2)"
  },

  chkOutPage: {
    lnkChkPage: 'div.brand-logo-checkout-header > a'
  },

  commPref: {
    lblHeader: "h1[class*='page-title']",
    mnuHeader: 'ol.breadcrumb-list li:nth-of-type(3)',
    lnkLeftPane: 'ul li:nth-of-type(2) a[href*="communication-preferences"]',
    lblPrefDesc: 'div.customer-service-content h3',
    lblTextDrawerHeader: 'h4 span',
    lblTextDrawerHeaderGuest: 'button[aria-controls="TextPreferenceDrawer"] h4',
    lblTextDrawerDesc: 'div[class*="text-preferences-drawer"] button p',
    btnTextDrawer: 'div[class*="text-preferences-drawer"]',
    lblEmailDrawerHeader: 'div[class="a11y-drawers undefined"] h4',
    lblEmailDrawerDesc: 'div[class="a11y-drawers undefined"] button p',
    btnEmailDrawer: 'div[class="a11y-drawers undefined"]',
    lblPhone: 'label[for="phone"]',
    chkCb2Text: 'input#cb2Checkbox',
    chkCrateText: 'input#cbCheckbox',
    chkKidsText: 'input#cbkCheckbox',
    lblCrateText: 'label[for="cbCheckbox"]',
    lblKidsText: 'label[for="cbkCheckbox"]',
    lblCb2Text: 'label[for="cb2Checkbox"]',
    btnSmsSignIn: 'button#smsBtn',
    lblSmsConsent: 'div#TextPreferenceDrawer p[class=text-preferences-message]',
    lblSuccessMsg: 'p[class="update-success-title"]',
    lblEmailSuccessMsgGuest: 'button[aria-controls="EmailPreferenceDrawer"] p[class="update-success-title"]',
    txtPhone: 'input[name="phone"]',
    lblOptInPhone: '[class="phone-number"]',
    lblUpdateTextOptIn: 'div.updated-text-opt-in b',
    lblUpdatedTextOptInBrand1: 'div.updated-text-opt-in p:nth-of-type(1)',
    lblUpdatedTextOptInBrand2: 'div.updated-text-opt-in p:nth-of-type(2)',
    lblUpdatedTextOptInBrand3: 'div.updated-text-opt-in p:nth-of-type(3)',
    lblUpdatedTextOptInMsg: 'div.updated-text-opt-in p:nth-of-type(4)',
    divTextDrawerExpand: 'p.update-success-title',
    lblEmailField: 'div[class="email-preferences-email"] b',
    lblEmailFieldGuest: 'div[class="email-preferences-email"] label',
    lblEmailAddress: 'div[class="email-preferences-email"] p',
    lblEmailDesc: 'form[class="email-preferences-opted-in"]  b:nth-of-type(1)',
    chkEmailCrate: 'input#crate',
    chkEmailKids: 'input#kids',
    chkEmailCb2: 'input#cB2',
    chkEmailHG: 'input#hudsonGrace',
    lblEmailCrate: 'label[for="crate"]',
    lblEmailKids: 'label[for="kids"]',
    lblEmailCb2: 'label[for="cB2"]',
    lblEmailHG: 'label[for="hudsonGrace"]',
    btnApplyChanges: 'button#subscribeBtn',
    lblEmailConsent: 'form[class="email-preferences-opted-in"] p[class="text-preferences-message"]',
    lblEmailUnsubscribe: 'form[class="email-preferences-opted-in"] b:nth-of-type(2)',
    btnUnsubscribe: 'button#unsubscribeBtn',
    lblUnsubscribeSuccess: 'p#unsubscribeMessage',
    chkTermsCrate: 'input#cbTermsCheckbox',
    lblTermsCrate: 'label[for="cbTermsCheckbox"]',
    chkTermsKids: 'input#cbkTermsCheckbox',
    lblTermsKids: 'label[for="cbkTermsCheckbox"]',
    chkTermsCB2: 'input#cb2TermsCheckbox',
    lblTermsCB2: 'label[for="cb2TermsCheckbox"]',
    txtEmail: 'input#email'
  },

  narvarPage: {
    lblItemTitle: 'h4[class*="return-summary-item"]',
    lblItemSku: 'li[class=" Sku"]',
    lblItemLocation: 'li[class=" DemandLocation"]',
    lblItemPrice: 'li[class=" item-price-display"]',
    lblItemQty: 'li[class=" return-item-qty"]'
  },

  cookieSetting: {
    lnkCookieSetting: 'button[class*=ot-sdk-show]',
    pupCookieSetting: 'div[class=ot-btn-container]',
    lblPopupHeader: '.ot-pc-header .ot-title-cntr h2',
    imgLogo: '.ot-pc-header .ot-pc-logo',
    mnuOption1: '.ot-cat-grp li:nth-of-type(1)',
    mnuOption2: '.ot-cat-grp li:nth-of-type(2)',
    mnuOption3: '.ot-cat-grp li:nth-of-type(3)',
    mnuOption4: '.ot-cat-grp li:nth-of-type(4)',
    mnuTitle1: '//div[contains(@class,"ot-tab-desc")]/div[1]//h4',
    mnuTitle2: '//div[contains(@class,"ot-tab-desc")]/div[2]//h4',
    mnuTitle3: '//div[contains(@class,"ot-tab-desc")]/div[3]//h4',
    mnuTitle4: '//div[contains(@class,"ot-tab-desc")]/div[4]//h4',
    mnuDesc1: '//div[contains(@class,"ot-tab-desc")]/div[1]/p',
    mnuDesc2: '//div[contains(@class,"ot-tab-desc")]/div[2]/p',
    mnuDesc3: '//div[contains(@class,"ot-tab-desc")]/div[3]/p',
    mnuDesc4: '//div[contains(@class,"ot-tab-desc")]/div[4]/p',
    btnConfirmChanges: 'button[class*=save-preference]',
    btnRejectAll: 'button[class*=ot-pc-refuse-all-handler]',
    btnAcceptAll: 'button[id=accept-recommended-btn-handler]'
  }
};
