module.exports = {
  SITECOMMON: {
    INTERUPTOR_POPUP_WINDOW: '#popup-content',
    INTERUPTOR_POPUP_CLOSE: '#popup-close',
    lblH1: '(//h1)[1]'
  },
  typeahead: {
    txtSearchInputBox: '[data-testid="site-search"] input',
    lblTypeaheadDropdown: '[data-sitesearch-testid="dropdown"]',
    lnkSearchSuggestions: '[data-group="Search Suggestions"] button',
    lnkProductSuggestions: '[data-group="Product Suggestions"] button',
    lblRecentsearchesHeader: 'h2[data-group="Recent Searches"]',
    lnkRecentSearches: '[data-group="Recent Searches"] span',
    lnkClearSearchHistory: '[data-sitesearch-testid="clear"]',
    lblRecentlyViewed: 'h2[data-group="Recently Viewed Products"]',
    lnkRecentlyViewed: 'ul[data-group="Recently Viewed Products"]'
  },
  searchResultsPage: {
    txtSearchInputBox: '[data-testid="site-search"] input',
    btnSearchSubmit: 'button[title="Search"]',
    lblH1PlpHeader: '.plp-header-search',
    lblNoSearchResultsMobileH1: '.top-section',
    lblRelatedSearches: '//h2[text()="Related Searches"]',
    lnkFirstRelatedSearches: '((//div[@data-testid="reveal-content"])[1]//li)[1]',
    lnkRelatedSearchesCount: '((//div[@data-testid="reveal-content"])[1]//li)',
    lblRelatedCategories: '//h2[text()="Related Categories"]',
    lnkFirstRelatedCategories: '((//div[@data-testid="reveal-content"])[2]//li)[1]',
    lnkRelatedCategoriesCount: '((//div[@data-testid="reveal-content"])[2]//li)',
    btnFilter: '//span[@class="filter-button-text"]',
    btnHideFilter: '//span[text()="Hide Filter"]',
    filterContainer: '//div[@class="filter-scroll-body-container"]',
    filterDrawersCount: '//span[@class="filter-type-title" and not(text()="Sort By")]',
    lblTypeFilter: '//span[text()="Type"]',
    lblColorFilter: '//span[text()="Color"]',
    lblPriceFilter: '//div[@class="drawer-header"]/span[text()="Price"]',
    lblMaterialFilter: '//span[text()="Material"]',
    lblWidthFilter: '//div[@class="drawer-header"]/span[text()="Width"]',
    lblResponsibleDesignFilter: '//span[text()="Responsible Design"]',
    lblTypeFacet: '//span[@class="checkbox-label-name"]',
    lnkAllTopFilters: '(//section[@class="current-selected-filters-container"]/button)',
    lnkTopTypeFilter: '(//section[@class="current-selected-filters-container"]/button)[2]',
    lnkTopColorFilter: '(//section[@class="current-selected-filters-container"]/button)[3]',
    lnkTopPriceFilter: '(//section[@class="current-selected-filters-container"]/button)[4]',
    lnkTopMaterialFilter: '(//section[@class="current-selected-filters-container"]/button)[5]',
    lnkTopResponsibleDesignFilter: '(//section[@class="current-selected-filters-container"]/button)[6]',
    lnkTopPriceRangeFilter: '(//section[@class="current-selected-filters-container"]/button)[2]',
    lnkTopWidthRangeFilter: '(//section[@class="current-selected-filters-container"]/button)[2]',
    lblColorFacet: '(//label[contains(@for,"Color_shadow")]/span)[1]',
    lblPriceFacet: '(//label[contains(@for,"Price_shadow")]/span)[1]',
    lblMaterialFacet: '(//label[contains(@for,"Material_shadow")]/span)[1]',
    lblWidthFacet: '(//label[contains(@for,"Width_shadow")]/span)[1]',
    lblResponsibleDesignFacet: '(//label[contains(@for,"Responsible_Design_shadow")]/span)[6]',
    txtMinValue: '#minValue',
    txtMaxValue: '#maxValue',
    btnRange: '.button-range-filter',
    lblRangeErrorMessage: '#range-filter-error-message',
    btnApplyFilter: '.filter-panel-footer >> text = APPLY',
    lnkTopClearAllFilter: '.clear-all-filter-button',
    lblViewAll: 'label[for=showAll]',
    lblReadyToShip: 'label[for=shipNow]',
    lblShipsWithin4Weeks: 'label[for=shipSoon]',
    lblZipCodeLocation: '.location-filter-container',
    lblZipCode: '//div[text=" Zip Code: "]',
    btnZipCode: '.reveal-content-toggle',
    txtZipCode: '#txtZipCode',
    btnApplyZipCode: '#applyZip',
    lblZipCodeErr: '#errorMsg',
    btnSort: '#top-container-sortBy-btn',
    btnSortByDropDown: '.dropdown-option-warp>li',
    lblMobileCurrentSortBy: '.current-sortBy',
    btnMobileSortByOptions: '.a11y-radio-label',
    lnkNew: '(//ul[@class="dropdown-option-warp"]/li)[6]',
    lnkMobileNew: '[for="top-container-sortBy5"]',
    lnkBestSelling: '(//ul[@class="dropdown-option-warp"]/li)[5]',
    lnkMobileBestSelling: '[for="top-container-sortBy4"]',
    stickyFilterContainer: '//div[@class="top-filters-container "]',
    cboTypeaheadDropDown: '#typeAhead-result-header',
    lblSearchSuggestions: 'ul[@id="typeAhead-result-header"]/li/div[text()="search suggestions"]',
    cboProductSuggestions: '//div[@class="typeahead-product-suggestions"]',
    lblProductSuggestions: '//div[@class="type-section-header"]',
    lnkFirstProduct: '(//div[@class="product-name"]/a)[1]',
    lblSKU: '(//span[@class="sku-title"])[2]',
    lblSKUMobile: '//span[@class="sku-title"]',
    btnMobileFilterApply: '//div[@class="filter-panel-footer"]//button[text()="APPLY"]',
    lblHeaderLogo: '.header-logo-container',
    btnViewMoreProducts: '//button[contains(text(),"View More Products")]',
    lblShowingProductCount: '.show-more-count , .progress-total-count',
    btnContinueToCanadaSite: '//button[text()="Continue to Canadian Site"]',
    lblRecentlyViewedDesktop: '#recently-viewed-products-track',
    lblRecentlyViewedMobile: '[data-name="Recently Viewed"]',
    lblSingleProduct: '.product-card',
    lblSingleProductName: '.product-name-text',
    lblSingleProductKids: '.product-kids-indicator'
  },

  searchNoResultsPage: {
    lblChatContainer: '#gladlyChat_container',
    txtResultsMessage: '#main h2',
    btnGiftRegistry: 'button[data-testid="search-no-results-registry-button"]',
    btnTrySearch: 'button[data-testid="search-no-results-search-button"]',
    btnShopNew: 'button[data-testid="search-no-results-new-arrivals-button"]',
    btnLetsChat: 'button[data-testid="search-no-results-chat-button"]',
    chatContainer: '#gladlyChat_container',
    lblRecentlyViewedDesktop: '#recently-viewed-products-track',
    lblRecentlyViewedMobile: '[data-name="Recently Viewed"]'
  },

  partialSearch: {
    lblPartialSearchCount: '.show-more-count , .progress-total-count'
  },

  productPage: {
    skuNum: '//span[@class="sku-number"]'
  },

  storesPage: {
    lblStoreListHeader: '.store-list-header',
    lnkViewAllStoresAndFacilities: '//a[text()="View All Stores & Facilities"]',
    lnkViewStoresByStateCB2: '.view-by-state-button',
    lnkBreadcrumbList: '.breadcrumb-list > li',
    lnkBreadcrumbs: '.breadcrumb-list',
    lnkStoresBreadcrumbMobile: '.mobile-breadcrumb-text',
    lnkStoresBreadcrumb: '//*[text()="Stores"]',
    lnkHomeBreadcrumb: '//a[text()="Home"]',
    lblH1: 'h1',
    lblViewByList: '#viewbylist',
    cmbStores: '//form[@id="frmStoresSearch"]//div//a',
    cmbDownArrowClick: '.icon-angle-down',
    cmbOptions: '//div[@class="dd"]//li',
    lblStoreByStateHeader: '.search-sub-header',
    lnkStateList: '//div[@class="state-list"]/ul/li',
    lblSeoCopyHeader: '.store-details > div > h2',
    lblSeoCopy: '.store-details > div > p',
    storeInfoContainer: '//div[contains(@class,"store-info-container")]',
    btnViewStoreDetails: '//a[contains(text(),"View Store Details")]',
    btnViewUpcomingEvents: '//a[contains(text(),"View Upcoming Events")]',
    lnkStateBreadcrumb: '//li/a[text()="',
    lnkStateBreadcrumbMobile: '//span[text()="',
    lblUpcomingStoreEvents: 'text = Upcoming Store Events',
    lnkPlusIcon: 'h2[class=store-name]'
  },

  storeLandingPage: {
    txtZipCode: '#keyword',
    btnFind: 'button[type="submit"]',
    lnkStoreDrawer: '.store-drawer-wrapper',
    btnAllStoreDrawers: '.a11y-drawer-button',
    btnViewStoreDetails: '[data-button="View Details"]',
    lnkTorontoStore: '#toronto330',
    lblFeatureCards: '.feature-card-container',
    btnFeatureCards: '.feature-card-container .button',
    lblStorePickupFAQ: '#global-popup',
    btnCloseStorePickupFAQ: '#popup-close',
    lblStoreListHeader: '.store-list-header',
    storeMap: '[data-testid="stores-map"]',
    lblStore: '[data-store-drawer]',
    lblStoreDistance: '.distance',
    lnkStoreLocation: '.locator',
    lnkStorePhone: '.phone-number',
    lblStoreHours: '.store-hours',
    lblStoreName: '.store-name',
    btnListOfStoreButtons: '[data-store-drawer] [data-button]',
    lblMyStore: '.my-store',
    lblZipCodeError: '#text-error-keyword',
    btnStoreFilters: '[data-testid="store-locator-filter"] [data-filter] label',
    btnStoreFilterCount: '[data-testid="store-locator-filter"] [data-filter] [data-count]',
    btnMobileFilterButton: '.filter-toggle-button',
    btnCloseFilter: 'close-filter-btn',
    btnCB2ViewAllStores: '[data-button="View All Stores"]',
    btnCB2StoresByState: '[data-button="View Stores by State"]',
    btnCB2CanadaWarehouse: '[data-country="Canada"] [data-testid="warehouse-card"]',
    btnCB2USWarehouse: '[data-country="U.S."] [data-testid="warehouse-card"]',
    btnFirstUSStore: '[data-country="U.S."] .store-card',
    lblFirstUSStore: '[data-country="U.S."] .store-card  h3',
    lblFirstCAStore: '[data-country="Canada"] .store-card h3',
    lblCB2StoreService: '.store-service-block',
    lnkCB2StoreService: '.store-service-block a'
  },

  storeDetailsPage: {
    lnkBreadcrumbList: '.breadcrumb-list > li',
    lnkViewAllStores: 'text = View All Stores',
    lblStoreName: 'h1',
    mapContainer: 'a[class="map-container static-map"]',
    btnMakeThisMyStore: 'text = Make This My Store',
    btnMyStore: '.my-store',
    lnkStoreAddress: '.store-address',
    btnFindANewStore: '[data-testid="find-store-button"]',
    lnkPhoneNumber: '//a[contains(@Class,"phone-number")]',
    lblStoreHoursContainer: '.store-hours-container',
    lblStoreStatus: '[data-testid="store-open-closed-label"]',
    lblSeeStoreHours: 'text = See Store Hours',
    lblStoreHours: '//ul[@data-testid="store-hours"]/li | //ul[@class="store-hours"]/li',
    lblRegistry: '.pubs-trans',
    lblFeatureIcons: '.feature-icons-container',
    btnGetDirections: '//button[@data-testid="get-directions-button"] | //a[text()="GET DIRECTIONS "]',
    lblCurbsidePickup: 'section[@class="store-detail-cms-block curb-side-pickup"]',
    lnkLearnMore: '//a[contains(@class,"pickup-link")]/span[text()="Learn more"]',
    lblCurbsideHeader: '.renewPopup > h2',
    btnCurbsideCloseIcon: '//button[@id="popup-close"]',
    lblStoreInformation: 'text = Store Information',
    lnkPickupDrawer: '.store-drawer-wrapper >> text = pickup',
    lnkParkingDrawer: '.store-drawer-wrapper >> text = parking',
    lnkDeliveryAndInstallationServices: '.store-drawer-wrapper >> text = DELIVERY AND INSTALLATION SERVICES',
    lnkReturnServices: '.store-drawer-wrapper >> text = return Policy',
    lnkCustomerService: '.store-drawer-wrapper >> text = customer Service',
    lblUpcomingStoreEvents:
      '(//span[@data-testid="section-title"])[1] | //h2[contains(@class, "store-event-Main-title")] | //span[@data-testid="events-carousel-title"]',
    lblStoreEventSubTitle: '(//span[@data-testid="section-subtitle"])[1] | //span[@data-testid="events-carousel-subtitle"]',
    lnkStoreEventCard: '//div[@data-testid="event"] | //div[@data-testid="store-event-card"]',
    imgContainer: '.image-container',
    lblInfoContainer: '.info-container',
    lblDay: '.info-container > div >> nth=0',
    lblDate: '.info-container > div >> nth=1',
    lblEventHeader: '//div[@data-testid="event"]//h3 | //h2[contains(@class, "event-header")]',
    lblDateTime: '//div[@data-testid="event"]//p | //div[contains(@class, "info-container")]/span',
    btnLearnMore: '//button[@data-testid="event-learn-more-button"] | //button[contains(@class, "learn-more-btn")]',
    lblStoreEventPopupHeader: '(//div[@data-testid="event-details-modal"]//span)[2] | //div[contains(@class, "store-event-pop-up")]/h2',
    lnkStoreEventPopupCloseCrate: '//button[@data-testid="modal-close-button"]',
    lnkStoreEventPopupCloseCB2: '//button[@id="popup-close"]',
    btnRSVP: '//button[@data-testid="event-rsvp-button"] | //div[contains(@class, "info-container")]/a',
    lblRSVPHeader: 'h1',
    lblNoRegistry: 'text=Don’t have a registry yet?',
    btnStartRegistryNow: 'text=Start Registry Now',
    lblRegistryTitle: '.create-registry-title',
    lblGuidance: '.new-registry-section',
    btnScheduleConsultation: 'text=Schedule Consultation ',
    lblAppointmentTypeHeader: '#header > #mainTitle',
    lblSeoCopy: '//div[@data-testid="store-seo-copy"] | //div[contains(@class, "seo-store-detail")]',
    lblSeoTitle: '.seo-store-detail > h2 , .section-seo-container > div > h2 , .reveal-content > h2, [data-testid="store-seo-copy"] h2',
    lblSeoContent: '.seo-store-detail > p , .section-seo-container > div > p , .reveal-content > p, [data-testid="store-seo-copy"] p',
    lblSeoStoreFaqs: '.seo-store-faqs',
    lblSeoStoreFaqTitle: '.seo-store-faqs > h2',
    lblSeoStoreFaqContent: '.seo-store-faqs-content',
    lblStoreFeaturesTitle: '(//span[@data-testid="section-title"])[2]',
    lblStoreFeaturesSubTitle: '//h3[@data-testid="section-subtitle"]',
    lblDesignServicesFeature: '[data-feature="design services"]',
    lblDesignServicesFeatureHeader: '[data-feature="design services"] h3',
    txtDesignServicesFeatureCopy: '[data-feature="design services"] p',
    btnDesignServicesFeature: '[data-feature="design services"] [data-testid="anchor-link"]',
    lblRegistryFeature: '[data-feature="registry consultations"]',
    lblRegistryFeatureHeader: '[data-feature="registry consultations"] h3',
    txtRegistryFeatureCopy: '[data-feature="registry consultations"] p',
    btnRegistryFeature: '[data-feature="registry consultations"] [data-testid="anchor-link"]',
    lblCareerFeature: '[data-feature="job opportunities"]',
    lblCareerFeatureHeader: '[data-feature="job opportunities"] h3',
    txtCareerFeatureCopy: '[data-feature="job opportunities"] p',
    btnCareerFeature: '[data-feature="job opportunities"] [data-testid="anchor-link"]',
    lblMostPopularItems: '.showcase-title > h2',
    lnkMostPopularItems: '.showcase-container',
    lnkMostPopularPrevIcon: '[data-testid="popular-items-carousel"] [aria-label="Previous Slide"]',
    lnkMostPopularNextIcon: '[data-testid="popular-items-carousel"] [aria-label="Next Slide"]',
    lnkPopularItemsCount: '[data-testid="product-card"]',
    btnSeeStoreServices: '#linkToStoreServices',
    servicesSection: '#store-services',
    lblFreeDesignConsultation: '.cms-secondary-title >> nth=0',
    lblInStoreShoppingAppointment: '.cms-secondary-title >> nth=1',
    lblPersonalShopper: '.cms-secondary-title >> nth=2',
    btnMeetLocally: '//a[text()="Meet locally "]',
    btnMeetVirtually: '//a[text()="meet virtually"]',
    btnAppointmentBookNow: '(//a[text()="Book now"])[1]',
    btnPersonalShopperBookNow: '(//a[text()="Book now"])[2]',
    txtFreeDesign: '.cms-text >> nth=0',
    txtAppointment: '.cms-text >> nth=1',
    txtPersonalShopper: '.cms-text >> nth=2',
    txtWeAreHiring: '.cms-text >> nth=3',
    txtCareers: '//h2[text() = "Careers"]/../p',
    lblStoreEventsHeader: '.half-width >> text = Store Events',
    imgStoreEventsImage: '.store-events-section > div > a > img',
    lblH2: '//h2[@class="cb2-brown-regular"]',
    lblH2Mobile: '(//h2[@class="cb2-brown-regular"])[1]',
    lblH3: '[class=cb2-brown-regular]',
    lblH3Mobile: '(//h2[@class="cb2-brown-regular"])[2]',
    txtStoreEventsCopy: '//p[@class="cb2-brown-light"]',
    btnBookYourAppnt: '//div[@class="services-blocks store-events-section"]//a[@class="button button-primary button-lg"]',
    lblWeAreHiring: '.half-width >> text = we’re hiring',
    lblCareers: '.store-careers >> text = Careers',
    lnkLearnMoreEvents: '.half-width >> text=LEARN MORE',
    lnkApplyNow: '.store-careers >> text=APPLY NOW ',
    lblPublicTransportation: 'text = Public Transportation',
    lblCratenoEventMessage: '.new-registry-section .title',
    lblCB2noEventMessage: '.no-events',
    btnPickupDrawar: '[data-testid="store-pickup-accordion"]',
    btnParkingDrawar: '[data-testid="store-parking-accordion"]',
    btnServicesDrawar: '[data-testid="store-services-accordion"]',
    btnReturnsDrawar: '[data-testid="store-returns-accordion"]',
    btnCustomerServiceDrawar: '[data-testid="store-customer-service-accordion"]',
    txtDrawarContent: '[data-testid="content-test-id"]'
  },
  storePickupPage: {
    txtPickUpFAQ: '.store-pickup-faq-container h3',
    lnkStorePickupFAQ: '.store-pickup a',
    lnkWarehousePickupFAQ: '.warehouse-pickup a',
    lblFAQPopup: '#popup-container',
    lblFAQPopupHeader: '#popup-container h1',
    btnCloseFAQPopup: '#popup-close',
    lblStoreListHeader: '.store-warehouse-header',
    lblStoresUSLocation: 'div[data-category="U.S. Stores"]>div',
    lblStoresCALocation: 'div[data-category="Canada Stores"]>div',
    lblWarehouseUSLocation: 'div[data-category="U.S. Warehouses"]>div',
    lblWareHouseCALocation: 'div[data-category="Canada Warehouses"]>div',
    btnStoresUSLocation: 'div[data-category="U.S. Stores"]>h3>button',
    btnStoresCALocation: 'div[data-category="Canada Stores"]>h3>button',
    btnWarehouseUSLocation: 'div[data-category="U.S. Warehouses"]>h3>button',
    btnWareHouseCALocation: 'div[data-category="Canada Warehouses"]>h3>button',
    btnExpandStoreUS: '(//div[@data-category="U.S. Stores"]//button)[2]',
    btnExpandStoreCA: '(//div[@data-category="Canada Stores"]//button)[2]',
    btnExpandWarehouseUS: '(//div[@data-category="U.S. Warehouses"]//button)[2]',
    btnExpandWarehouseCA: '(//div[@data-category="Canada Warehouses"]//button)[2]',
    lblStoreNameUS: 'div[data-category="U.S. Stores"] .store-name',
    lblStoreNameCA: 'div[data-category="Canada Stores"] .store-name',
    lblWarehouseNameUS: 'div[data-category="U.S. Warehouses"] .store-name',
    lblWarehouseNameCA: 'div[data-category="Canada Warehouses"] .store-name',
    btnViewStoreDetailsUS: 'div[data-category="U.S. Stores"] .btn-view-info',
    btnViewStoreDetailsCA: 'div[data-category="Canada Stores"] .btn-view-info',
    btnViewWarehouseDetailsUS: 'div[data-category="U.S. Warehouses"] .btn-view-info',
    btnViewWarehouseDetailsCA: 'div[data-category="Canada Warehouses"] .btn-view-info',
    btnPlusIcon: '(//div[contains(@class,"store-container")]//i)[1]'
  },

  seoGeneratedPage: {
    lblSeoPageTitle: '//h1',
    lnkSeoPage: '//a[@class="search-sitemap-result"]',
    lblSeoPlpHeader: '//h1[@class="plp-header"]',
    btnFilter: '.filter-bar-main, .filter-bar-fieldset >> button',
    lblHideFilter: '//span[@class="filter-button-text"]',
    btnCloseFilter: '[data-testid="modal-close-button"]',
    lblTotalProductCount: '.item-count',
    btnSortByDropDown: '#top-container-sortBy-btn',
    btnMobileSortByDropDown: '.drawer-header >> span >> nth=1',
    lnkMostRelevant: '(//ul[@class="dropdown-option-warp"]/li)[1]',
    lnkPriceLowToHigh: '(//ul[@class="dropdown-option-warp"]/li)[2]',
    lnkMobilePriceLowToHigh: '[for="top-container-sortBy1"]',
    lnkPriceHighToLow: '(//ul[@class="dropdown-option-warp"]/li)[3]',
    lnkMobilePriceHighToLow: '[for="top-container-sortBy2"]',
    lnkTopRated: '(//ul[@class="dropdown-option-warp"]/li)[4]',
    lnkMobileTopRated: '[for="top-container-sortBy3"]',
    lnkNew: '(//ul[@class="dropdown-option-warp"]/li)[5]',
    lnkMobileNew: '[for="top-container-sortBy5"]',
    lblProductsCount: '.product-detail-description',
    lblPriceElement: 'div >> nth=1',
    lblSalePrice: '.salePrice',
    lblRegularPrice: '.regPrice',
    lblRating: '.review-stars-bar',
    lblNew: '//*[@class="product-new"] | //div[contains(text(),"New")]',
    lblRelatedCategories: '//h2[text()="Related Categories"]',
    lnkRelatedCategoriesCount: '//ul[@id="seo-categories"]/li',
    seoContainer: '//div[@class="section-seo-container"]',
    lblSeoCopyHeader: '//div[@class="section-seo-container"]//h2',
    lblSeoCopy: '//div[@class="section-seo-container"]//p | //div[@class="section-seo-container"]/div',
    lblPriceFacetCount: '(//label[contains(@for,"Price_shadow")]/span)',
    lnkFirstRelatedCategories: '(//ul[@id="seo-categories"]/li)[1]'
  },

  StoreListStatePage: {
    lnkViewAllStoresAndFacilities: 'text = View All Stores & Facilities',
    lnkStateName: 'text = '
  },

  StoreDetailsPage: {
    btnViewStoreDetails: 'text = View Store Details',
    lnkStoreName: '//button//span[text()="',
    btnViewStoreDetail: '//parent::div/ancestor::button/parent::h2/following-sibling::div//a[text()="View Store Details"]',
    seoHeader1Tag: 'h1',
    lnkCb2StoreName: '//h3[text()="',
    txtLocationInputText: '#keyword',
    btnFind: 'text = Find'
  },
  headerStoreLocatorPopUp: {
    shippingTo: '.header-zip-text',
    MobileFindStore: '.header-no-store-link',
    findStore: '//span[text()="Select My Store"]',
    headerStoreLocatorIcon: '//a[contains(@class,"header-location-link")] | //button[contains(@class,"header-location-icon")]',
    zipCodedisplay: '.zip-code-display',
    txtZipCode: '#txtZipCode',
    applyZip: '#applyZip',
    headerStoreName: '.header-store-name',
    txtStoreZipCode: '.store-zip-input',
    mobileStoreZipCode: '#keyword',
    submitZipCode: '.zip-submit-button',
    mobileSubmitZipCode: '.search-submit-button',
    lnkViewAllStores: '//a[text()="View all stores"] | //a[text()="View All Stores & Facilities"]',
    lblStoreName: 'h1',
    lblUpcomingStoreEvents: '.store-event-Main-title',
    btnMakeThisMyStore: 'text = Make This My Store >> nth=1',
    mobilebtnMakeThisMyStore: 'text = Make This My Store',
    btnStoreWrapper: '.nearby-stores-list button >> nth=0',
    mobilebtnStoreWrapper: '.nearby-stores-list button >> nth=0',
    btnViewStoreInfoandEvents: '.stores-link >> nth=0',
    mobilebtnViewStoreDetails: '//a[contains(text(),"View Store Details")]',
    mobilebtnViewUpcomingEvents: '//a[contains(text(),"View Upcoming Events")]',
    lnkStoreAddress: '((//div[@class="store-details-expanded"])[1]/span[@class="store-address"])[1]',
    lnkPhoneNumber: '((//div[@class="store-details-expanded"])[1]/span[@class="store-address"])[3]',
    lblStoreHours: '.store-hours >> nth=0',
    mobilelnkStoreAddress: '.store-address',
    mobilelnkPhoneNumber: '.phone-number',
    btnMyStore: '.header-store-name',
    lnkHeaderPhoneNumber: '.header-store-phone',
    lblHeaderStoreHours: '//div[@id="header-store-hours"]//ul/li',
    lnkHeaderstoredetailslink: '#header-store-details-link',
    lnkChangeMyStore: 'text = Change My Store',
    lnkAllStores: '#header-all-stores-link',
    mobilelnkAllStores: 'text = All Stores >> nth=1',
    errorMsg: '#errorMsg'
  }
};
